hashicorp/terraform-plugin-sdk

internal/lang/funcs/number.go
internal/lang/funcs/number_test.go
internal/lang/functions.go
internal/lang/functions_test.go

Cherry-picks hashicorp/terraform#22747.

lang/funcs: parseint function (cherry-pick hashicorp/terraform#22747)

---

terraform/context.go
terraform/context_apply_test.go
terraform/context_plan_test.go

Cherry-picks hashicorp/terraform#22783.

core: Warn when creating and applying with -target (cherry-pick hashicorp/terraform#22783)

---

helper/resource/state_shim.go

Cherry-picks hashicorp/terraform#22837.

don't lose track of private data in the ACC tests (cherry-pick hashicorp/terraform#22837)

---

terraform/graph_builder_import.go

Cherry-picks hashicorp/terraform#22855.

command/import: fix error during import when implied provider was not used (cherry-pick hashicorp/terraform#22855)

---

internal/lang/funcs/cidr.go
internal/lang/funcs/cidr_test.go
internal/lang/functions.go
internal/lang/functions_test.go

Cherry-picks hashicorp/terraform#22858.

lang/funcs: cidrsubnets function (cherry-pick hashicorp/terraform#22858)

---

terraform/context_refresh_test.go
terraform/node_data_refresh.go
terraform/testdata/plan-data-depends-on/main.tf

Cherry-picks hashicorp/terraform#22895.

ensure data sources are always written to state (cherry-pick hashicorp/terraform#22895)

---

.github/CONTRIBUTING.md

Clarify policy on cosmetic PRs. Inspired by https://github.com/rails/rails/blob/master/CONTRIBUTING.md#did-you-fix-whitespace-format-code-or-make-a-purely-cosmetic-patch and the associated GitHub comment https://github.com/rails/rails/pull/13771#issuecomment-32746700.

Add note to CONTRIBUTING.md regarding cosmetic PRs

---

scripts/cherry_pick/IGNORE_FILES

Core vendors dependencies as its a binary, we want to only cherry pick the code changes and not vendor anything

ignore vendor during cherry picks

---

terraform/context_apply_test.go
terraform/node_module_removed.go
terraform/testdata/apply-targeted-resource-orphan-module/child/main.tf
terraform/testdata/apply-targeted-resource-orphan-module/main.tf

This commit was generated from hashicorp/terraform#22811.

Cherry pick hashicorp/terraform#22811

---

internal/initwd/from_module_test.go
internal/initwd/module_install_test.go

This commit was generated from hashicorp/terraform#22918.

Cherry pick hashicorp/terraform#22918

---

internal/addrs/parse_ref.go
internal/addrs/parse_ref_test.go
internal/lang/data.go
internal/lang/data_test.go
internal/lang/eval.go
internal/lang/eval_test.go
terraform/context_apply_test.go
terraform/eval_apply.go
terraform/evaluate.go
terraform/testdata/apply-invalid-index/main.tf

This commit was generated from hashicorp/terraform#22846.

Cherry pick hashicorp/terraform#22846: Always evaluate resources in their entirety

---

helper/resource/testing.go
helper/resource/testing_test.go

Previously, the `-sweep-run` filtering would only add sweepers matching the filter, but miss the dependencies. In real world usage:
```go
resource.AddTestSweepers("aws_vpc", &resource.Sweeper{
Name: "aws_vpc",
Dependencies: []string{
"aws_egress_only_internet_gateway",
"aws_internet_gateway",
"aws_nat_gateway",
"aws_network_acl",
"aws_route_table",
"aws_security_group",
"aws_subnet",
"aws_vpc_peering_connection",
"aws_vpn_gateway",
},
F: testSweepVPCs,
})
```
Where resources like `aws_subnet` would contain further dependencies that would cause failures if not removed, e.g.
```console
$ go test ./aws -v -timeout=10h -sweep=us-west-2 -sweep-run=aws_vpc -sweep-allow-failures
...
2019/10/27 16:10:29 [DEBUG] Sweeper (aws_vpc) has dependency (aws_egress_only_internet_gateway), but that sweeper …
```

helper/resource: Ensure -sweep-run filtering includes sweeper dependencies

---

helper/validation/int.go
helper/validation/int_test.go
helper/validation/list.go
helper/validation/list_test.go
helper/validation/network.go
helper/validation/network_test.go
helper/validation/strings.go
helper/validation/strings_test.go
helper/validation/time.go

Also fixed `UniqueStrings` to ensure all elements are of test string and adds some better tests

Validation - Rename some validators to make names more consistant

---

helper/schema/resource_data.go

See #312 for more details. A follow up PR will remove the feature from the V2 branch.
closes #312

Deprecate Partial State

---

helper/schema/resource_data.go
helper/schema/resource_data_test.go

Partial State will be deprecated in #317 and land on V1. This will remove the feature in V2.

Remove partial state

---

helper/acctest/random.go
helper/acctest/random_test.go

As per the original ticket (#171).

helper/acctest: fix RandIntRange

---

helper/resource/state_shim.go
helper/resource/testing.go
helper/resource/testing_test.go
terraform/resource_mode_string.go

These identifiers were restored in the acctest driver rebase, they have been re-pruned or re-privatized.

Rebase cleanup

---

go.mod
go.sum

Updates to go-plugin 1.2.0 which enables grpc reflection

Enable GRPC reflection

---

helper/resource/state.go
helper/resource/wait.go
helper/schema/provider.go
helper/schema/provider_test.go
helper/schema/resource.go
helper/schema/resource_importer.go
helper/schema/resource_importer_test.go
helper/schema/resource_test.go
internal/helper/plugin/grpc_provider.go

Removes context aware Exists function added in the context work and deprecates exists.

Deprecate Exists

---

helper/schema/resource.go

Remove unnecessary comment

---

helper/schema/schema.go
helper/schema/schema_test.go

Port new RequiredWith feature to V2

Cherry pick #342 to V2

---

helper/resource/testing_new.go

This is a port of https://github.com/hashicorp/terraform-plugin-sdk/pull/356 to v2.

v2: omit test cleanup when state is empty

---

helper/resource/testing.go

This is a port of https://github.com/hashicorp/terraform-plugin-sdk/pull/378 to v2.

v2: Binary testing - Fix cleanup of temporary directories

---

helper/resource/testing.go
helper/resource/testing_test.go

The tests needed to change since the V2 setup is a bit different

Port mockT panic pattern to V2

---

helper/schema/schema.go
helper/schema/schema_test.go

Reference: #416
Reference: #418 (v2 fix)

helper/schema: Allow self references with AllowOneOf, ExactlyOneOf, and RequiredWith in InternalValidate [v1]

---

.circleci/config.yml
scripts/release/release.sh

Backport of https://github.com/hashicorp/terraform-plugin-sdk/pull/401 to v1-maint

allow releases from v1-maint branch

---

helper/resource/testing.go
helper/resource/testing_new_config.go
terraform/state.go

For now the error message will simply state it's not possible. Once we have a set of prescribed upgrade techniques we will update this messaging.

Port TypeSet Heuristic

---

helper/schema/core_schema.go
helper/schema/core_schema_test.go

Export StringKind alias

---

scripts/release/release.sh

fixes #444 
Consolidate regex for semver version into `semverRegex` variable, which captures the _version core_ (e.g. 1.2.3) and _version prerelease_ (e.g. rc.1) in two separate capture groups.
Write the appropriate values for `SDKVersion` and `SDKPrerelease` in `meta.go`. 
Commits in this PR test the following behaviours in order:
- `SDKVersion` is set to `"0.0.1"`
- `SDKPrerelease` is set to `"rc.1"`
- version number in commit (and tag, not shown) is set to `0.0.1-rc.1`
- `SDKVersion` is set to `"0.0.2"`
- `SDKPrerelease` is set to `""`
- version number in commit (and tag, not shown) is set to `0.0.2`
When this PR is approved, I will reset back to https://github.com/hashicorp/terraform-plugin-sdk/pull/448/commits/793ec14c19b3a389d7e95c47d89038103e7e6a7d to remove the test commits.

fix meta.SDKPrerelease parsing

---

go.mod
go.sum

Update to take advantage of the bugfix in terraform-plugin-test v1.4.4
that fixes #495.

Update terraform-plugin-test to v1.4.4.

---

internal/helper/plugin/grpc_provider.go

It is common to want a global stop context passed to the provider configure
function. Unfortunately the grpc ctx is request scoped and cancels after
the function returns. This makes saving/resusing a global ctx impossible.
This hack will attach a global stop synchronized context... onto the ctx
passed into the provider config function. The reason this is done is to
avoid an API signature breaking change, this feature should also be hidden
as we would prefer providers use the request scoped and deadlined contexts
passed into the CRUD functions over a global one.

Fix goroutine leak, expose global stop ctx

---

go.mod
go.sum
helper/resource/testing_new_config.go

This restores output similar to V1 of the SDK
Closes #454

Capture plan and render for unexpected diffs

---

helper/resource/testing_new_config.go

Closes #540
Please let me know if you would like to do some other form of logging, etc. instead. 👍

helper/resource: Remove extraneous ExpectNonEmptyPlan success logging

---

helper/resource/testing_new.go

testing: Add err != nil check before calling ErrorCheck?

---

helper/resource/testing_new_config.go

Use correct function and remove ending exclamation mark.

Fix warnings around errors

---

go.mod
go.sum

Contains some bug fixes we want, like a fix for panics when calling
Stop.

Update plugin-go to 0.2.1.

---

ROADMAP.md

Update our roadmap to reflect current work and priorities.

Update ROADMAP.md for Q1 2021.

---

helper/resource/testing_new.go

Pass predestroy state to CheckDestroy

---

SUPPORT.md

Link to the support policy of v1 from the main branch's support policy.

Link to v1-maint support policy.

---

go.mod
go.sum

Run `go mod tidy` after recent dependency changes.

Run `go mod tidy`.

---

ROADMAP.md

Update the ROADMAP to reflect Q3's priorities.

Update ROADMAP.md for Q3

---

ROADMAP.md

We were using calendar year quarters, but we decided to update to fiscal year quarters.

Fix dates on Q3 roadmap

---

SUPPORT.md

Reflect v1's EOL status in SUPPORT.md.

Update for v1 EOL

---

go.mod
go.sum

go get github.com/hashicorp/terraform-exec@v0.15.0

---

helper/validation/time.go

I noticed this while working on a project. Thanks for Terraform!

Fix a tiny typo in the time helper docs

---

.changelog/913.txt
helper/resource/plugin.go
internal/plugintest/environment_variables.go
internal/plugintest/helper.go
internal/plugintest/working_dir.go

internal/plugintest: Set CHECKPOINT_DISABLE=1 in terraform-exec directly

---

helper/schema/resource.go

helper/schema: Update Go documentation for StateUpgradeFunc

---

helper/schema/schema.go

Compile `isValidFieldName` regex once

---

website/docs/plugin/sdkv2/index.mdx

Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/626
Reference: https://github.com/hashicorp/terraform-docs-common/pull/252
Further encourage framework usage after GA release.

website: Update overview page for framework GA

---

website/docs/plugin/sdkv2/best-practices/deprecations.mdx
website/docs/plugin/sdkv2/best-practices/detecting-drift.mdx
website/docs/plugin/sdkv2/best-practices/index.mdx
website/docs/plugin/sdkv2/best-practices/sensitive-state.mdx
website/docs/plugin/sdkv2/best-practices/testing.mdx
website/docs/plugin/sdkv2/debugging.mdx
website/docs/plugin/sdkv2/guides/terraform-0.12-compatibility.mdx
website/docs/plugin/sdkv2/guides/v1-upgrade-guide.mdx
website/docs/plugin/sdkv2/guides/v2-upgrade-guide.mdx
website/docs/plugin/sdkv2/index.mdx
website/docs/plugin/sdkv2/logging/http-transport.mdx
website/docs/plugin/sdkv2/logging/index.mdx
website/docs/plugin/sdkv2/resources/import.mdx
website/docs/plugin/sdkv2/resources/index.mdx
website/docs/plugin/sdkv2/resources/retries-and-customizable-timeouts.mdx
website/docs/plugin/sdkv2/resources/state-migration.mdx
website/docs/plugin/sdkv2/schemas/index.mdx
website/docs/plugin/sdkv2/schemas/schema-types.mdx
website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
website/docs/plugin/sdkv2/testing/acceptance-tests/sweepers.mdx
website/docs/plugin/sdkv2/testing/acceptance-tests/testcase.mdx
website/docs/plugin/sdkv2/testing/acceptance-tests/teststep.mdx
website/docs/plugin/sdkv2/testing/index.mdx

- Migrates the formats of links in Markdown content as part of the [Docs Content Link Rewrites project](https://docs.google.com/document/d/1WaSyvoVPS-YCNiSPX0ynGpvc1gySEcpbrRoQVhimQCA/edit)
These are all the links that were determined to be "unrewriteable" (AKA no rewrite needed to be applied based on the rewrite script's logic):
<details>
<summary>🌟 Expand for lists of links by file name</summary>
```JSON
{
"website/docs/plugin/sdkv2/best-practices/depending-on-providers.mdx": [
"https://github.com/hashicorp/terraform/issues/new",
"https://github.com/hashicorp/terraform/tree/main/docs/plugin-protocol"
],
"website/docs/plugin/sdkv2/best-practices/deprecations.mdx": [
"#provider-attribute-removal",
"#provider-attribute-rename",
"#renaming-a-required-attribute", …
```

docs: Migrate link formats

---

website/docs/plugin/sdkv2/testing/acceptance-tests/testcase.mdx

Update it to v2 to reflect the latest (SDK) code.

Update the Target of `TestCase` Source Code Link to be SDK V2

---

.github/CODEOWNERS

Adding permission to adjust:
- docs
- images
- website's README

adjust permissions for docs files

---

helper/schema/provider.go
helper/schema/resource.go
helper/schema/resource_test.go
helper/schema/schema.go
helper/schema/schema_test.go

Addresses https://github.com/hashicorp/terraform-plugin-sdk/pull/1444#discussion_r1999465390 and continues #1444 by adding internal identity validation, which is mostly contained in [this commit](https://github.com/hashicorp/terraform-plugin-sdk/pull/1447/commits/253b60ef96c766decdf99f0a34ea84d151e5aa14) minus a [linting fix](https://github.com/hashicorp/terraform-plugin-sdk/pull/1447/commits/a2d383bb6ea0f24e14bfbf2ae83afe123443bf88)

Resource Identity: Add internal validation

---

.changes/unreleased/NOTES-20250418-154446.yaml

chore: Add changelog for beta.1 release

---

helper/schema/testing.go

TFECO-9280: Add `TestResourceDataWithIdentityRaw` test helper

---

.changes/unreleased/BUG FIXES-20250424-133143.yaml

Add changie entry for write-only update method validation bugfix
