hashicorp/terraform-plugin-sdk

- scripts/cherry_pick/cherry_pick.sh
- scripts/cherry_pick/commit.sh
Split out the part of the cherry-pick script that makes the commit and amends the message.
If a merge conflict interrupts `cherry_pick.sh` before the commit, you can now resolve the merge conflict and then run `commit.sh HASH` to preserve commit information (including author).
> split cherry-pick script

- scripts/cherry_pick/IGNORE_FILES
- scripts/cherry_pick/cherry_pick.sh
Cherry-picking Core PRs often results in `website/` files being added, which is incorrect. We can't ignore all added files as we still want new files in relevant subdirectories. Without bringing back the whitelist, this PR solves the problem quickly and safely by unstaging added files that match the `IGNORE_FILES` regex.
> cherry_pick.sh: unstage added ignored files

- CHANGELOG.md
- scripts/release/release.sh
v1.1.0 incorrectly reports `SDKVersion` as v1.0.0 in `meta/meta.go`. This is due to a bug in the release script, which we failed to notice in the rush of https://github.com/hashicorp/terraform-plugin-sdk/pull/51.
This PR corrects the bug in the script. After this is merged I will release v1.1.1, which will report its version correctly.
fixes #190
> Correctly update SDKVersion during release

- helper/resource/testing.go
- helper/resource/testing_test.go
Due to various circumstances, such as a remote API unexpectedly breaking compatibility in a dependency sweeper, it can be desirable to allow the sweepers to continue after failures. This gives the operator the opportunity to try cleaning up other, unrelated infrastructure by using a new `-sweep-allow-failures` flag.
It is still up to the resource implementations to allow continuing on failures within the same sweeper, rather than exiting on the first failure encountered.
Without new flag (same previous behavior on successful sweepers):
```console
$ go test ./aws -v -sweep=us-west-2 -sweep-run=aws_dx_gateway_association_proposal -timeout 10h
2019/10/08 11:39:30 [DEBUG] Running Sweepers for region (us-west-2):
2019/10/08 11:39:30 [DEBUG] Running Sweeper (aws_dx_gateway_association_proposal) …
```
> helper/resource: Introduce sweeper flag to continue other sweepers after failures

- .hashibot.hcl
Simply label an issue `provider/<name>` and it will be migrated just like how Core is handled. The `name` is lifted from the label and the repo name is constructed as `<new_owner>/<repo_prefix><name>`
> hashibot: configure provider org migrator

- terraform/context_apply_test.go
- terraform/context_plan_test.go
- terraform/eval_for_each.go
- terraform/node_data_refresh.go
- terraform/terraform_test.go
- terraform/testdata/plan-for-each-unknown-value/main.tf
This commit was generated from hashicorp/terraform#22597.
> Cherry pick hashicorp/terraform#22597: Ensure for_each values wholly known for sets

- helper/validation/validation.go
- helper/validation/validation_test.go
Add `StringDoesNotContainAny()`, a validator to ensure that the provided value does not contain any of the specified Unicode code points in chars.
```console
$ make test
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/acctest	0.016s
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/customdiff	0.017s
?   	github.com/hashicorp/terraform-plugin-sdk/helper/encryption	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/hashcode	0.001s
?   	github.com/hashicorp/terraform-plugin-sdk/helper/logging	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/mutexkv	0.052s
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/pathorcontents	0.008s
ok …
```
> Add 'StringDoesNotContainAny' validation function

- helper/validation/validation.go
- helper/validation/validation_test.go
Add `FloatAtLeast()` and `FloatAtMost()`, validators to ensure that the provided value is at least a specified value and at most a specified value, respectively.
Pulled over from https://github.com/terraform-providers/terraform-provider-aws/pull/2477.
```console
$ make test
go test ./...
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/acctest	(cached)
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/customdiff	(cached)
?   	github.com/hashicorp/terraform-plugin-sdk/helper/encryption	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/hashcode	(cached)
?   	github.com/hashicorp/terraform-plugin-sdk/helper/logging	[no test files]
ok …
```
> Add 'FloatAtLeast' and 'FloatAtMost' validation functions

- helper/validation/validation.go
- helper/validation/validation_test.go
Add `StringDoesNotMatch()`, a validator to ensure that the provided value does NOT match a given regular expression.
Pulled over from https://github.com/terraform-providers/terraform-provider-aws/pull/9941.
```console
$ make test
go test ./...
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/acctest	(cached)
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/customdiff	(cached)
?   	github.com/hashicorp/terraform-plugin-sdk/helper/encryption	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/hashcode	(cached)
?   	github.com/hashicorp/terraform-plugin-sdk/helper/logging	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/mutexkv	(cached)
ok …
```
> Add 'StringDoesNotMatch' validation function

- helper/schema/resource_data.go
- helper/schema/resource_data_test.go
~I'm open to bikeshedding on the function name. Strongest alternative probably `HasChanges` (this alternative just "feels better" than `HaveChange` I may switch if there is support for it)?~ Voted on `HasChanges` Practically speaking we could have switched `HasChange` itself to be variadic and it likely wouldn't have broken anything in the real world, however from a compiled language/type signature point of view anyone who has assigned this method (unlikely) would experience a breaking change (the rare L for compiled languages).
Also I'm allowing a noop call `d.HasChanges()` I wasn't sure maybe it should panic without a single key? Could change signature to
```
func (d *ResourceData) HasChanges(firstKey string, others ...string) bool
```
Closes #194
> ResourceData: create variadic 'HasChanges' method

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
This is to forward questions to our forum a bit more aggressively by hiding link to blank issues and making links to the forum more visible. I also added links to help users navigate in case they have anything provider-related or core-related.
> github: Add issue templates & links

- .github/ISSUE_TEMPLATE/config.yml
This is already being added automatically due to repository having SECURITY.md so I'm just removing the duplicate.
> github: Remove link to security vulnerability

- helper/resource/testing.go
- helper/resource/testing_test.go
Closes https://github.com/hashicorp/terraform-plugin-sdk/issues/278.
Without the fix the new test cases cause a crash:
```console
$ go test ./helper/resource/...
2019/12/12 07:57:21 [DEBUG] New state was assigned lineage "7d80f5ca-2c51-4290-c29e-0df3b7ff4e30"
2019/12/12 07:57:21 [DEBUG] Waiting for state to become: [done]
2019/12/12 07:57:21 [TRACE] Waiting 10ms before next try
2019/12/12 07:57:21 [TRACE] Waiting 10ms before next try
2019/12/12 07:57:21 [TRACE] Waiting 10ms before next try
2019/12/12 07:57:21 [TRACE] Waiting 10ms before next try
2019/12/12 07:57:21 [DEBUG] Waiting for state to become: [done]
2019/12/12 07:57:21 [TRACE] Waiting 10ms before next try
2019/12/12 07:57:21 [TRACE] Waiting 10ms before next try
2019/12/12 07:57:21 [TRACE] Waiting 10ms before next try
2019/12/12 …
```
> Don't crash when dependent test sweeper is missing

- helper/schema/schema.go
- helper/schema/schema_test.go
Fixes #280 
---
I also added some more tests to check that the same bug doesn't affect `ConflictsWith` or `AtLeastOneOf` - it doesn't, but it's IMO useful to have the test there to ensure it stays that way.
--- 
The reason `ConflictsWith` isn't affected is because it runs after we check for unknowns:
https://github.com/hashicorp/terraform-plugin-sdk/blob/6184b3148aaf867395a78e1dd1a84592f8484de3/helper/schema/schema.go#L1417-L1433
I decided not to move things around in the main `validate()` as there is a risk of introducing some more unknown edge cases when folks combine `ConflictsWith`, `AtLeastOneOf` and `ExactlyOneOf`.
Perhaps that code deserves some cleanup, but I think it's safer to leave it for later, bigger refactoring and/or for when we introduce cty here.
--- 
I guess the reason …
> schema/ExactlyOneOf: Fix handling of unknowns in complex types

- helper/resource/testing.go
Currently, a missing dependent sweeper has a log level of `[DEBUG]`. Since this is likely a logic error in the provider, this should be a `[WARN]` to raise the visibility.
> Changes log level for missing dependent sweepers

- helper/validation/uuid.go
- helper/validation/uuid_test.go
Just a (nitpicky) patch to align the function name with others and clarify the purpose of the function a bit.
I would be also 👌  with `IsUUID` or `ValidUUID`, but the function name should IMO communicate that it's positive validation.
> helper/validation: UUID -> IsUUID

- helper/resource/wait.go
- helper/resource/wait_test.go
Reference: https://github.com/hashicorp/terraform/pull/17220
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/9779#discussion_r315176586
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/9812#discussion_r315457893
It is currently possible to introduce subtle bugs or crashes when using `resource.RetryableError` and `resource.NonRetryableError` and allowing a `nil` error input. This PR proposes behavior that requires providers to be explicit with their usage of these errors, otherwise returns a bug reporting message to the operator.
For example (https://github.com/terraform-providers/terraform-provider-aws/blob/4c0387645f982ddcd51b3ffe2cc8992c06fb9c2c/aws/resource_aws_elastic_beanstalk_application.go#L105):
```go
var app …
```
> helper/resource: Require explicit usage of NonRetryableError and RetryableError

- CHANGELOG.md
- acctest/helper.go
- go.mod
- go.sum
- helper/resource/state_shim.go
- helper/resource/testing.go
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
- helper/resource/testing_new_import_state.go
- helper/resource/testing_new_test.go
This PR adds a new optional test driver for Terraform provider acceptance tests that runs the Terraform CLI.
To minimise work for provider developers at this stage, the API follows as closely as possible the functionality of the legacy test driver, minimising changes needed to acceptance test code.
Since we are targeting a 1.x.x release of the provider SDK, no breaking changes will be made, and the legacy test driver will only be removed in version 2.0.0.
The new test driver must be enabled by initialising the test helper in the [`TestMain()`](https://golang.org/pkg/testing/#hdr-Main) function in all provider packages that run acceptance tests. Most providers have only one package.
Import the new `"github.com/hashicorp/terraform-plugin-sdk/acctest"` package and add the following …
> Binary acceptance test driver

- helper/schema/serialize.go
- helper/schema/serialize_test.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/7198
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/10045
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/10339
Reference: https://github.com/hashicorp/terraform/pull/22719
When a resource schema contains the following:
```go
"config_block_attribute": {
Type:     schema.TypeSet,
Computed: true,
Elem: &schema.Resource{
Schema: map[string]*schema.Schema{
"attribute1": {
Type:     schema.TypeBool,
Computed: true,
},
"attribute2": {
Type:     schema.TypeString,
Computed: true,
},
},
},
},
```
The TypeSet hash values were previously all collapsed to the zero-value, which meant that multiple set entries were lost. Here we check that all of the attributes …
> helper/schema: Do not collapse TypeSet hash values when configuration block contains only Computed attributes

- helper/resource/state.go
- helper/resource/state_test.go
- helper/resource/wait.go
- helper/resource/wait_test.go
Creates a context aware `resource.RetryContext` and `resource.StateChangeConf.WaitForStateContext`.
Cancellation/deadline of the passed in context is respected. If `WaitForStateContext` returns due to context cancellation/deadline the resulting `context.DeadlineExceeded` or `context.Canceled` error is returned but the LastResult is not returned. If the passed in timeout is exceeded and we are in the graceful shutdown period, context cancelation will exit the grace period early, however the returned error will still be of type `*resource.TimeoutError`.
Context was not pulled through to the `Refresh` functions, these functions are often (if not always?) closed over within a CRUD method and if the context is needed within that scope it is in scope (much like `meta`).
```
func create(ctx …
```
> Context aware StateChangeConf

- helper/resource/testing.go
V2 of the SDK removes the internalized version of terraform core. Acceptance tests can now only be ran via the binary driver. Test cases can no longer opt out.
> Mandatory Binary Driver

- helper/schema/schema.go
- helper/schema/schema_test.go
Reference: https://github.com/bflad/tfproviderlint#standard-schema-checks
These `Schema` fields are only intended for configurable attributes.
> helper/schema: Additional validation for non-configurable attributes

- helper/schema/field_reader_config.go
- helper/schema/schema.go
- helper/schema/schema_test.go
- helper/schema/shims_test.go
Reference: https://github.com/bflad/tfproviderlint/blob/master/passes/S034/README.md
> helper/schema: Remove PromoteSingle from Schema

- helper/schema/field_reader_config.go
- helper/schema/schema.go
- helper/schema/set.go
- internal/helper/plugin/grpc_provider.go
V2 of the SDK only runs through protocol 5. This is technically a breaking change since `schema.SetProto5()` was public, however it should never have been called by providers.
> Remove protocol 5 feature flag

- helper/validation/strings.go
- helper/validation/strings_test.go
Add `StringNotInSlice()`, a validator to ensure that the provided value does NOT match the value of any element in the specified string slice.
```console
$ make test
go test ./...
?   	github.com/hashicorp/terraform-plugin-sdk/acctest	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/acctest	(cached)
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/customdiff	(cached)
?   	github.com/hashicorp/terraform-plugin-sdk/helper/encryption	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/hashcode	(cached)
?   	github.com/hashicorp/terraform-plugin-sdk/helper/logging	[no test files]
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/mutexkv	(cached)
ok …
```
> Add 'StringNotInSlice' validation function

- helper/schema/schema.go
- helper/schema/schema_test.go
Reference: https://github.com/bflad/tfproviderlint/blob/master/passes/S022/README.md
The current behavior of these attributes in Terraform Plugin SDK v1.7.0 is similar to `map[string]string`, which is confusing for nested schema with multiple types.
For example, the following schema:
```go
"permissions": {
Type:     schema.TypeMap,
Optional: true,
Elem: &schema.Resource{
Schema: map[string]*schema.Schema{
"type": {
Type:     schema.TypeString,
Required: true,
ValidateFunc: validation.StringInSlice([]string{
ssm.DocumentPermissionTypeShare,
}, false),
},
"account_ids": {
Type:     schema.TypeString,
Required: true,
},
},
},
},
```
Results in the following potential configuration:
```hcl
permissions = {
type        = "Share"
account_ids = "all"
}
```
Which works fine, but also allows (which …
> helper/schema: Additional Schema validation for TypeMap with Elem *Resource

- helper/resource/testing.go
- helper/resource/testing_test.go
Closes #334
Also consolidates the unit testing for the function.
> helper/resource: Return error with TestCheckResourceAttrPair() when comparing self

- helper/schema/resource_data_test.go
- helper/schema/schema.go
- helper/schema/schema_test.go
opt out with Go parsable boolean (False, false, FALSE, 0). In the case where a value is set but is not a parsable boolean, a warning is logged but true is the default to remain backwards compatible with the previous implementation (where opt in involved setting the env var to anything).
> TF_SCHEMA_PANIC_ON_ERROR on by default

- plugin/grpc_provider.go
- plugin/serve.go
A missed `&` causes the struct to be passed by value and thus it no longer implements the `plugin.GRPCPlugin`. Tracing the code through `go-plugin`, a default for netrpc is selected if the grpc interface is not implemented.. which caused an initial handshake error. The struct also previously embedded the `plugin.Plugin` interface... which allows it to satisfy the interface even though calling a method would panic? (I'm not sure how that works..) for clarity the implementation was made explicit but now the "dummy" methods return an error if they are ever called, the SDKv2 will ONLY implement GRPC server plugins.
> Fix plugin.Serve

- helper/schema/resource_data.go
Taking a harder stance and really discouraging the use of this method. It will be deprecated but I would not remove it in V2.
closes #283
> Deprecate GetOkExists

- CHANGELOG.md
- helper/resource/testing.go
Fixes #352.
This runs `Configure()` on providers prior to the binary acctest run, so they can access `provider.Meta()` during tests.
The one nuance to be aware of here is that `PreCheck()` is called after the auto-configure, in case providers are already using this for custom configuration.
Once this is approved I'll generate CHANGELOG and raise another PR to the `version2` branch.
> auto-configure providers during binary acctests

- Makefile
The gofmtcheck.sh script uses the gofmt -s flag for reporting simplification issues, so the fixing command must also include this flag.
> Makefile: Update fmt target to include gofmt -s flag

- CHANGELOG.md
- helper/resource/testing.go
Fix a bug in which temporary directories created during a binary test run were not cleaned up at the end of the run.
> Binary testing: Fix cleanup of temporary directories

- helper/schema/schema.go
- helper/schema/schema_test.go
This PR contains 
the new `RequiredWith` schema validation check (including unit tests), and
The new `RequiredWith` schema validation check, complements the existing `ExactlyOneOf`and `AtLeastOneOf` in the way that when the schema field has an assigned value, **all** fields listed must have assigned values as well.
The new `RequiredWith` validation check allows building (mutual) dependencies over multiple schema fields, whereas the existing `ExactlyOneOf` and `AtLeastOneOf` checks only ensure fulfilled dependencies with only one other schema field.
> RequiredWith schema check and changes in validation for optional schema fields 

- helper/resource/testing_new.go
Fixes https://github.com/hashicorp/terraform-plugin-sdk/issues/347
The legacy test framework does not attempt a post-test destroy step when there is no state: https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/resource/testing.go#L701
This was missed out of the new framework, with the consequence that successful tests that do not create resources would error during cleanup.
We add this check back, in new binary testing style - the nuance here being that our state may well contain modules but no resources.
Again, I'll raise a separate PR to the `version2` branch after review.
> Binary testing: omit test cleanup when state is empty

- go.mod
- go.sum
This release adds `helper.GetPluginName()` and improves parallel test performance for large providers.
> upgrade to terraform-plugin-test@v1.3.0

- helper/resource/testing.go
- helper/resource/testing_test.go
The current `mockT` did not halt execution on `Fatal`, this led to a test failure as the SDK code expects `t.Fatal` to halt execution. This introduces a panic and recover to fix the unit test. Future use of the mock (if there are any) should follow the same pattern
> Make mockT.Fatal halt execution

- helper/validation/map.go
- helper/validation/map_test.go
Add various validators for Map keys and values:
* `MapKeyLenBetween` validates that the provided value is of type map and the length of all keys are between `min` and `max`
* `MapValueLenBetween` validates that the provided value is of type map and the length of all values are between `min` and `max`
* `MapKeyMatch` validates that the provided value is of type map and all keys match a given regex
* `MapValueMatch` validates that the provided value is of type map and all values match a given regex
```console
$ make test
go test ./...
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/acctest	(cached)
ok  	github.com/hashicorp/terraform-plugin-sdk/helper/customdiff	(cached)
? …
```
> Add various Map key and value validators

- .circleci/config.yml
- scripts/release/release.sh
After `master` is switched to v2, we need to be able to release from both the v2 branch and the v1 branch (`v1-maint`).
This PR updates the CircleCI config so that v1 releases can be triggered from `v1-maint` just as they are triggered from `master`. 
Please note that the version tagged and released is always parsed from the `(Unreleased)` line in the CHANGELOG. The v1 maintenance branch should have an up-to-date 1.x CHANGELOG that does not include any v2 versions. The internal release documentation has been updated to note this.
> v2: allow releases from v1-maint branch

- helper/resource/testing.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/12147
To help provider developers find implementation errors with test sweepers.
> v2/helper/resource: Return error when test sweeper dependency is not found, instead of logging warning

- helper/resource/testing.go
- helper/resource/testing/testing.go
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
- helper/resource/testing_new_import_state.go
- helper/resource/testing_test.go
- helper/schema/testing.go
- helper/validation/testing.go
This PR scrubs the SDK surface of uses of Go's `testing` package, `testing.T` and `testing.M` were exposed to the SDK surface as an oversight in V1. It instead propagates the interface previously known as `resource.TestT` with a few added signatures so it can be compatible with a testing interface present in `terraform-plugin-test` (the driver library for acceptance tests). The interface had to be moved to its own package (now `helper/resource/testing`) to avoid circular imports.
Ideally we could remove any imports of Go's`testing` in non `_test.go` files from the SDK. However the acceptance test framework checks if `go test` was called with verbose enabled. This reference could not be removed unless we remove that requirement.
> Unexpose testing pkg

- helper/schema/provider.go
- helper/schema/resource.go
- helper/schema/resource_data.go
- internal/helper/plugin/grpc_provider.go
- terraform/state.go
Port the functionality added in hashicorp/terraform#22583 that allows
providers to receive arbitrary, provider-definable module-scoped
information from configs.
> Port provider_meta functionality from core.

- helper/schema/schema_test.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/issues/71
Reference: https://github.com/bflad/tfproviderlint/issues/104
The `TestSchemaMap_InternalValidate` tests also include TODOs for potential schema validation improvements.
> tests/helper/schema: Add unit testing covering existing behavior of ConflictsWith and list index/map key syntax

- helper/schema/schema.go
- helper/schema/schema_test.go
Reference: #71
Reference: #407 (v2 pull request)
> helper/schema: Additional validation for schema attribute references [v1]

- helper/schema/schema.go
- helper/schema/schema_test.go
Rebased #365
Reference: #71
Builds on testing from https://github.com/hashicorp/terraform-plugin-sdk/pull/364 (targeting v1). This PR currently targets v2.
> helper/schema: Additional validation for schema attribute references

- helper/resource/testing.go
- helper/resource/testing_new.go
This was a minor oversight in V1, no reason for this to be public at this time.
> privatize RunNewTest

- helper/resource/testing.go
- helper/resource/testing_new_config.go
- terraform/state.go
This change can assist users when enabling the binary driver. Previously any checks that addressed through TypeSet hashes would error confusingly (just claim the resource does not exist) as the binary driver's shimmed state did not represent TypeSet addresses.
A small hack/flag needed to be added onto `terraform.State`, but the docs clearly state it's not for external use.
> TypeSet Check Heuristic

- helper/schema/field_reader.go
- helper/schema/resource.go
- helper/schema/schema.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/pull/414
Reference: https://github.com/golang/go/wiki/Deprecated
The `Removed` field and associated handling has been removed in version 2.
> helper/schema: Mark Schema.Removed, SchemasForFlatmapPath(), and (Resource).SchemasForFlatmapPath() as Deprecated [v1]

- helper/schema/schema.go
- helper/schema/schema_test.go
Reference: #407
Reference: #416
> helper/schema: Allow self references with AllowOneOf, ExactlyOneOf, and RequiredWith in InternalValidate

- helper/schema/schema.go
- helper/schema/schema_test.go
The validation for `AtLeastOneOf`, `ConflictsWith`, `ExactlyOneOf`, and `RequiredWith` should not flag configuration block attributes without `Type: TypeList` and `MaxItems: 1` if they are the last part of the reference.
Previously:
```
--- FAIL: TestSchemaMap_InternalValidate/RequiredWith_string_syntax_with_list_configuration_block (0.00s)
schema_test.go:5037: "RequiredWith string syntax with list configuration block": Unexpected error occurred: RequiredWith: test configuration block reference (config_block_attr) can only be used with TypeList and MaxItems: 1 configuration blocks
--- FAIL: TestSchemaMap_InternalValidate/AtLeastOneOf_string_syntax_with_set_configuration_block (0.00s)
schema_test.go:5037: "AtLeastOneOf string syntax with set configuration block": Unexpected error occurred: …
```
> helper/schema: InternalValidate fix for configuration block type checking [v1]

- helper/schema/schema.go
- helper/schema/schema_test.go
The validation for `AtLeastOneOf`, `ConflictsWith`, `ExactlyOneOf`, and `RequiredWith` should not flag configuration block attributes without `Type: TypeList` and `MaxItems: 1` if they are the last part of the reference.
Previously:
```
--- FAIL: TestSchemaMap_InternalValidate/RequiredWith_string_syntax_with_list_configuration_block (0.00s)
schema_test.go:5037: "RequiredWith string syntax with list configuration block": Unexpected error occurred: RequiredWith: test configuration block reference (config_block_attr) can only be used with TypeList and MaxItems: 1 configuration blocks
--- FAIL: TestSchemaMap_InternalValidate/AtLeastOneOf_string_syntax_with_set_configuration_block (0.00s)
schema_test.go:5037: "AtLeastOneOf string syntax with set configuration block": Unexpected error occurred: …
```
> helper/schema: InternalValidate fix for configuration block type checking

- acctest/doc.go
Updated wording reflecting the mandatory nature of the binary driver in V2.
> Port acctest docs from V1

- helper/schema/set.go
- helper/schema/set_test.go
> Fix HasChange when using nested schema.Set

- helper/encryption/encryption.go
In line with
https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#don-39-t-encrypt-state,
mark all the functions in helper/encryption as deprecated and up for
removal in v2.
> Deprecate helper/encryption.

- scripts/release/release.sh
Our regexp used to only accept [0-9].[0-9].[0-9] release numbers. This
change updates the regexp to allow an optional -[0-9a-zA-Z.] suffix to
the release, for prereleases.
> Fix regex in release.sh to accept prereleases.

- helper/resource/testing.go
This allows us to roll this out by Service Package, rather than by individual Test Case
From the Azure Providers perspective that means we can configure this in [the Kotlin Settings](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/.teamcity/components/settings.kt#L18) on a per-package basis along with the other per-package options (like parallelism, and eventually locations)
> helper/resource/testing: allowing disabling Binary Testing via an Environment Variable

- helper/resource/testing.go
Reference: https://github.com/golang/go/wiki/Deprecated
So linters can detect its pending removal.
> helper/resource: Comment update DisableBinaryDriver to mark as deprecated

- helper/hashcode/hashcode.go
- helper/mutexkv/mutexkv.go
- helper/pathorcontents/read.go
- httpclient/useragent.go
> Deprecated packages that were removed in v2

- helper/resource/testing_test.go
- helper/schema/resource_data.go
- helper/schema/resource_data_test.go
- helper/schema/schema.go
- helper/schema/schema_test.go
Schema errors will panic if TF_ACC is set, panicking is no longer on by default
but cannot be opted out of when running acceptance tests. This does not address #455 .
Technically a breaking change `schema.PanicOnErr` is no longer an exported var
Closes #451
> Remove TF_SCHEMA_PANIC_ON_ERR

- helper/schema/resource_data.go
The key specific partial flagging though is still deprecated. 
This method may still be renamed in v2.0.0, but the functionality will be retained.
> Removing deprecation for Partial mode

- helper/schema/serialize.go
- helper/schema/serialize_test.go
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13549
This may only be an issue with Terraform 0.11 and earlier with an obscure schema of:
```go
"attr": {
Type:     schema.TypeSet,
Optional: true,
Elem: &schema.Schema{
Type: schema.TypeMap,
Elem: &schema.Schema{
Type: schema.TypeString,
},
},
},
```
And having the following Terraform configuration:
```hcl
resource "example_thing" "example" {
attr = [{
somekey = true
}]
}
```
Previously, this would panic (with updated test):
```console
$ go test ./helper/schema -run=TestSerializeForHash
--- FAIL: TestSerializeForHash (0.00s)
panic: unknown value type in TypeMap bool [recovered]
panic: unknown value type in TypeMap bool
goroutine 5 [running]:
testing.tRunner.func1.1(0x1a4a5e0, 0xc0004b9920) …
```
> helper/schema: Support serialization of bool values in TypeMap values [v1]

- helper/resource/plugin.go
- helper/resource/testing.go
In version 1.0.0-1.6.0, our in-process non-binary test driver didn't
call go-plugin, and called log.SetOutput to control what got logged, to
avoid flooding test output with debug logs.
From version 1.6.0, the in-process non-binary test driver had the same
behavior, but we added an out-of-process binary test driver, which used
go-plugin, but had the provider in a separate process that sent its
stdout and stderr through Terraform. Terraform then, not the test
framework, was responsible for filtering the output.
With the introduction of our in-process binary test driver, however,
we're using go-plugin and Terraform isn't filtering log output for us.
In theory, the log.SetOutput call that was working for the in-process
non-binary test driver should've worked here, as well, and it sort of
did. …
> Fix test logging output.

- go.mod
- go.sum
Improves the auto-install `terraform` feature. Other improvements since v1.3.0 include a bug fix for init and further `WorkingDir` helpers.
> terraform-plugin-test v1.4.3

- helper/resource/testing_new.go
We had a call to `getState` outside the `runProviderCommand` helper
function, which timed out, as it couldn't connect to the provider it was
looking for.
Moving it inside the provider makes TestIDRefresh work again.
> Fix TestIDRefresh to not timeout.

- go.mod
- helper/schema/provider.go
- internal/helper/plugin/context/context.go
- internal/helper/plugin/grpc_provider.go
Follows up on stop context work. This exposes a helper to be called within a provider configure function. The use is deprecated. A new nested packaged was created to for the key definition due to a circular import if `helper/schema` tried to import `internal/helper/plugin`
```
func providerConfigure(ctx context.Context, d *schema.ResourceData) (interface{}, diag.Diagnostics) {
stopCtx, ok := schema.StopContext(ctx)
...
}
```
> Create StopContext helper function

- helper/resource/state.go
- helper/resource/wait.go
- helper/schema/provider.go
- helper/schema/resource.go
- helper/schema/resource_importer.go
- helper/schema/schema.go
Large providers will experience warning spam, this actually overloads our acceptance testing setup on some larger tests with nesting. All these methods have been marked deprecated in the godoc anyways.
> Remove spammy warnings

- helper/logging/logging.go
- helper/resource/plugin.go
- helper/resource/testing.go
Restore the ability to split out logging by test name when using the
acceptance test framework.
Note: I'm not sure if this will have race conditions, given it's called
repeatedly.
> Restore test log splitting.

- helper/resource/testing.go
- helper/resource/testing_new.go
Users used to specify third-party providers they relied on for
tests--usually utility providers like random--by importing the provider
and specifying it in resource.TestCase.Providers or
resource.TestCase.ProviderFactories. With binary testing, this is no
longer necessary, as the providers can be downloaded from the registry
using Terraform init. This allows for more up-to-date providers with
fewer Go dependencies, which is a nicer system all around.
The acceptance testing framework will run `terraform init`, which will
automatically notice these providers being used in the configuration
files and download them, just like in production.
However, there's a wrinkle; tests that import don't have the resources
set in the configuration, which means they're not downloaded during
init, which …
> Allow specifying external providers in a TestCase.

- helper/resource/testing_new_config.go
Our test steps handle refreshes very explicitly, which is good. But we
don't actually refresh before applying the step, assuming the previous
step left our state in a good condition.
However, this means that if a config changes the value of a data
source--e.g., for a data source that generates JSON from HCL, as is
common in IAM resources--the data source's value in state won't be
updated before apply, meaning the resources depending on that data
source value will have a stale, incorrect value instead of the one in
the config.
As we advise users to not run Terraform with -refresh=false, this
doesn't mirror the user experience in production and is confusing--I
lost several hours to debugging it.
This PR explicitly runs refresh prior to applying or planning a test
step, so new data source …
> Refresh before applying test step.

- helper/resource/testing.go
Don't allow TestCases to have providers set with the same local name in
ExternalProviders and ProviderFactories.
> Disallow collisions between external providers and factories.

- helper/resource/testing_new_config.go
When running provider commands, rather than using the Require* versions
that call t.Fatal, call the non-Require* versions that just return the
error. The TestStep sometimes has expected errors, and we need to bubble
the errors up to be potentially handled instead of just failing
immediately.
> Return config errors during TestSteps.

- helper/resource/testing.go
- helper/resource/testing_test.go
The reference is widespread enough that there's no value to having providers internalize this variable. I do think it's the SDK's responsibility to publish this information, should the framework want to change the name of the env var.
> Restore TestEnvVar

- helper/resource/testing_new.go
Number now indexes starting from 1 and includes total count ex: `Step 1/3 error:...`.
Closes #520
> Restore step number in err msg

- helper/resource/testing_new_import_state.go
Fixes https://github.com/hashicorp/terraform-plugin-sdk/issues/531
Update importStateCheck to ready from the import workspace
> fix importStateCheck to read from import workspace

- helper/resource/testing_new_import_state.go
Closes https://github.com/hashicorp/terraform-plugin-sdk/issues/521.
The AWS provider has not quite upgraded to v2.0.0 of the SDK yet so I haven't been able to test the fix against my failing acceptance test case although the same fix against v1.14.0 succeeded.
I see no suitable unit tests to add a test case to.
> Consider resource provider when locating expected state in ImportState acceptance test case

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Updates the Issue templates to use the v2 package path for querying the version
> Update Issue template instructions to query v2 package

- helper/resource/testing_new_import_state.go
Closes #533
I have a feeling that #552 probably fixed #533, but this is an optimization and could prevent bugs if the old state contains a matching managed resource and data source of the same exact type.
Please let me know if you would prefer a different solution here or would like me to create issues for and implement any of these:
- Splitting this `ImportStateVerify` handling into its own unit test-able function
- Adding the `Mode` field to `ResourceState`
> helper/resource: Skip data sources in ImportStateVerify testing

- helper/resource/testing_new.go
- helper/resource/testing_new_import_state.go
Closes #532 
`testStepNewImportState` can now return the error (if any) of the underlying method that imports the resource, thus allowing for error handling w/in `runNewTest` when `step.ImportState` is set to `true`. Special error handling is needed here to account for provider acceptance tests that check for expected errors during `ImportState` test steps as illustrated in #532. 
Output of previously failing acceptance test:
```
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_basic (303.34s)
```
> helper/resource/testing_new: update import state testing

- helper/resource/testing_new_config.go
> helper/resource: Always return the error in testStepNewConfig instead of t.Fatalf() so step numbers are included with error messages

- go.mod
- go.sum
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
- helper/resource/testing_new_import_state.go
Backport including step number in error messages, backport fix to use correct state when conducting import tests, and backport better diffs in error messages.
This backports #552, #526, and #524.
> Backport fixes to reattach testing.

- README.md
Update the support policy information on the v1-maint branch, to
document v1's support policies. This basically adds information on our
Go support policy and simplifies the Terraform support policy to only be
about v1, and adds information on reattach binary acceptance testing.
> Update v1's support policy information.

- README.md
Drop information about what versions of Terraform v1 of the SDK
supports; it doesn't matter, v1 can document that on its own branch.
Add information about what versions of Go the SDK supports.
> Update support policies.

- helper/resource/testing_new_import_state.go
We were using the wrong WorkingDir when doing reattach import testing in
v1. This is fixed in v2, but hasn't been backported yet, apparently.
> Fix import when reattach testing in v1.

- helper/resource/testing_new_import_state.go
When testing and verifying that the imported state matches the applied
state, we're seeing some resources report that the number of elements in
the `timeouts` map don't match between the two states. Apparently, any
timeouts set in the config are added to state during _import_, but
aren't during a regular apply.
To avoid returning this incorrectly as a diff, we're just not going to
verify that.
> Fix spurious diff from timeouts.

- README.md
Add a link to the README for the v2 upgrade guide, and another to the great tutorial the learn.hashicorp.com site has.
We should probably holistically redesign this README at some point, but that feels like a problem for another day.
> Add v2 Upgrade Guide and Learn docs to the README

- helper/resource/testing_new.go
We were silently discarding the error instead of surfacing it when there
was an error returned from our post-test destroy code responsible for
tearing down infrastructure. Let's tell the user so they know
infrastructure may be dangling, and can see what went wrong and ideally
fix it.
Fixes #571.
> Check the error on post-test destroy.

- helper/resource/testing_new_config.go
TestSteps do a number of things: first they apply a config, then they
run some checks on that config, then they do a plan _without_
refreshing, then refresh, then do _another_ plan.
When you tell a TestStep you expect a non-empty plan, _right now_ it
expects _both_ those plans to come back empty. Pre-binary testing,
however, it only required the second one to come back non-empty.
This matters because some providers overload TestChecks to modify
resources out of band. When this is done, there's a plan without a
refresh (that won't see the modifications) and a plan after a refresh
(that will see the changes). If both are forced to agree on whether the
plan should be empty or not, you can't use that pattern anymore, because
they can't _both_ be right.
This restores the original behavior of …
> Restore pre-binary testing ExpectNonEmptyPlan behavior.

- helper/resource/testing_new_import_state.go
Resolve the issue with spurious test failures with ImportStateVerify from resources using timeouts on the v1-maint branch, as well.
> Backport #576: fix importstateverify + timeouts.

- go.mod
- go.sum
When an unexpected diff occurs, return the human-readable plan output,
instead of JSON.
A previous version of terraform-plugin-test/terraform-exec didn't
support reading the non-JSON plan file. Update to latest to have the
function do what it was meant to.
> Restore human-friendly plan output.

- go.mod
- go.sum
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
Backport #580 to restore pre-binary ExpectNonEmptyPlan behavior when
testing.
Backport #584 to use the latest terraform-exec and terraform-plugin-test
to take advantage of the fixed diff output.
Backport #581 to check the error on post-test destroy, warning there may
be dangling resources and surfacing the error.
This should bring the v1-maint branch in line with 2.0.3 in terms of
functionality and bug fixes.
> Backport remaining fixes from v2.0.3.

- helper/resource/testing_new.go
Currently, the CheckDestroy function is being passed the state after the destroy occurs. In most cases, the resources will be empty so the function can't verify that the resources have been disposed / handled as expected.
I wrote up a discuss [post](https://discuss.hashicorp.com/t/checkdestroy-functionality/14615) here with some more details.
According to the documentation, the CheckDestroy method **‘receives the last known Terraform state as input’**.
The comment in the code says: **'CheckDestroy is called after the resource is finally destroyed to allow the tester to test that the resource is truly gone’**.
The documentation for the CheckDestroy type states: the **‘TestCheckFunc is the callback type used with acceptance tests to check the state of a resource. The state passed in is the …
> Pass pre-destroy state to CheckDestroy as expected by the documentation

- go.mod
- go.sum
- helper/resource/plugin.go
- helper/resource/testing.go
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
- helper/resource/testing_new_import_state.go
- internal/plugintest/config.go
- internal/plugintest/doc.go
- internal/plugintest/guard.go
- internal/plugintest/helper.go
- internal/plugintest/util.go
- internal/plugintest/working_dir.go
Include terraform-plugin-test as an internal package, called internal/plugintest. After this is merged I will import relevant issues and PRs from the tftest repository and archive or transfer it.
Remove the `Require*` versions of the Terraform functions, as these are not necessary.
> internal/plugintest pkg (formerly terraform-plugin-test)

- helper/resource/testing_new.go
Closes #593
Can confirm with this fixes the given acceptance test case while not presenting unexpected errors with other similar data source testing not using ExpectNonEmptyPlan.
> helper/resource: Remove data source exclusion from ExpectNonEmptyPlan handling

- helper/resource/testing_new_config.go
- internal/plugintest/working_dir.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/pull/578
Closes #604
Restores v2.0.3 behavior and renames the function slightly for additional clarity on its intent.
Previously with consistently failing provider check:
```
=== CONT  TestAccAWSDmsReplicationTask_basic
TestAccAWSDmsReplicationTask_basic: resource_aws_dms_replication_task_test.go:18: Step 1/3 error: After applying this test step, the plan was not empty.
stdout:
{"format_version":"0.1","terraform_version":"0.12.29","planned_values":{"root_module":{"resources":[{"address":"aws_dms_endpoint.dms_endpoint_source","mode":"managed","type":"aws_dms_endpoint","name":"dms_endpoint_source","provider_name":"aws","schema_version":0,"values":{"certificate_arn":"","database_name":"tf-test-dms-db","elasticsearch_settings":[],"en …
```
> internal/plugintest: Output saved plans in human readable format

- helper/schema/resource.go
- helper/schema/resource_test.go
Fixes #607
Currently in the `InternalValidate` validation, we prohibit any explicit overriding of the `id` attribute for resources in favor of writing an explicit version. But this does not allow modifying the `Optional` bit, or setting a custom `Description` which is useful for docs generation and the language server. This allows implementers to override the `id` if they so choose as long as it still adheres to the rules specified for the built-in usage.
> Relax validation of ID attribute

- helper/resource/testing_sets.go
- helper/resource/testing_sets_test.go
These helpers are essential when migrating a provider that relies heavily on TypeSet to V2 of the SDK
Closes #595
> Port TypeSet helpers from AWS

- helper/schema/resource_data.go
- helper/schema/resource_data_test.go
Closes #457
Reference: https://github.com/hashicorp/terraform-plugin-sdk/pull/458 (original v1 PR)
Allows provider developers to simplify conditional logic on disproportionate attribute set sizes, essentially "any but this one" or "any but these few".
> helper/schema: Introduce ResourceData type HasChangeExcept and HasChangesExcept receiver methods

- helper/resource/error.go
- helper/resource/wait.go
To help support the [Go 1.13 `error` enhancements](https://blog.golang.org/go1.13-errors), i.e. `errors.Is()`, `errors.As()` and the `%w` verb, this PR adds the `Unwrap()` function to the exported errors from the SDK.
> Adds Unwrap function to SDK errors

- diag/helpers.go
Allow `nil` error values to be passed to `diag.FromErr`. This makes using `diag.FromErr` much more ergonomic when porting providers using the v1 SDK to the v2 SDK.
This semantic would have been useful in preventing https://github.com/digitalocean/terraform-provider-digitalocean/issues/505 which occurred because a `return err` was refactored to `return diag.FromErr(err)` in the v2 SDK upgrade without performing a `nil` check (as solved by https://github.com/digitalocean/terraform-provider-digitalocean/pull/506).
> handle nil error values in diag.FromErr

- go.mod
- go.sum
- plugin/serve.go
Update go-plugin, so that it no longer overrides the default output in the `log` package.
Go-plugin can transfer JSON structured hclog output to a client logger. Rather than requiring existing providers to update all logging calls, we inject a wrapper into the std log package output which translates the defacto log format into structured log output with the correct levels. This will allow terraform to correctly filter the output, rather than default to handling all logs as Debug. This allows the logger to remove redundant tags and timestamps in the log output, and fixes multi-line log output where the first line may have a tag other than `[DEBUG]`, but the remainder of the lines will be converted to `[DEBUG]`.
This PR intends to only configure the logging when running as a plugin. The …
> Update go-plugin, and use hclog.Logger when serving a plugin

- helper/validation/meta.go
- helper/validation/meta_test.go
- helper/validation/testing.go
Adds a wrapper function for validation functions of type `SchemaValidateFunc` (https://github.com/hashicorp/terraform-plugin-sdk/issues/534). 📦
It follows a similar implementation as currently used in `schema.validateFunc` ([schema.go#L441-L456](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/schema/schema.go#L441-L456))to handle legacy validation functions. This implementation parses the last step of given `cty.Path` to be used as the second parameter of the legacy validator.
This would help a lot of projects since no "diag" versions of the validation helpers are implemented yet.
> helper/validation: Wrapper function for legacy SchemaValidateFunc

- helper/resource/plugin.go
We don't need to reach out to checkpoint when running tests, so disable
that information. Fixes #640.
Also remove our logging override, as we've updated to a version of
go-plugin that doesn't require that anymore. See also #661.
> Disable checkpoint during tests.

- helper/resource/plugin.go
Missed a logging override in #663. This should fix the last of the race
condition where logging can get written to stderr unexpectedly during
tests. We no longer need to do this because go-plugin was fixed and we
upgraded in #639. We don't want to overwrite that fix in tests.
> Drop logging override.

- helper/resource/plugin.go
- plugin/serve.go
When testing, we don't want to override where log output gets sent--the
test framework takes care of that itself. go-plugin has disabled its use
of log.SetOutput for us, but #639 introduced a log.SetOutput in
plugin.Serve. This adds a plugin.ServeOpt property to disable that
log.SetOutput call so we can finally have tests where log lines don't
randomly show up in test output.
> Stop overriding log output in plugin.Serve in tests

- helper/schema/grpc_provider.go
Our Timeouts code can't handle it yet.
> Stop using json.Number when decoding Private.

- helper/resource/testing_sets.go
- helper/resource/testing_sets_test.go
I encountered a panic when I have a hierarchical attribute where the depth of the hierarchy isn't necessarily the same for all  objects. The panic is caused by an out of bounds slice index in cases where you specify an attribute path greater than or equal to the deepest structure in state when using `TestCheckTypeSetElemNestedAttrs()`.
example - Let's say there are groups that can have sub-groups. Your state contains 4 groups and three of them are in a chain and the other has no sub-groups:
```
group1 <- group 2 <- group3
group4
```
When a unit test tries to match `TestCheckTypeSetElemNestedAttrs("groups.*.groups.*.groups.*", map[string]string{"name": expectedName})`, it will panic because `groups.*.groups.*.groups.*` causes the check to index too far into group4.
> Avoid panics when testing nested sets of varying depth

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Update the issue templates to show a command that retrieves the current
version of the module without relying on jq or any other tooling beyond
the `go` command.
Fixes #641.
> Use better command for module version detection.

- helper/schema/schema.go
Our current diagnostic only surfaces that a required argument was not
set, but doesn't actually tell you which one. This updates the error
message to match the error returned by core, which includes the name of
the field that's missing.
Why do we return an error if core returns an error? Because core returns
the error only for required _attributes_, because as far as core is
concerned, there is no such thing as required blocks. Only attributes
can have flags, and "required" is a flag, so there can't be "required"
blocks.
But historically blocks have been able to be required, so the SDK fakes
it by doing provider-side validation on the block. But the error message
was less than helpful. This fixes the error message to be more
actionable.
Fixes #535.
> Surface the required block that's missing in the error.

- go.mod
- go.sum
- internal/plugintest/helper.go
- internal/plugintest/working_dir.go
Terraform 0.15 deprecates a number of CLI arguments, including the `[DIR]` positional argument used in `terraform init` and `terraform apply`. The binary test framework made use of these arguments as a way of working around plugin source limitations in v1. This workaround is no longer needed.
The main difference here is that previously we would instantiate one `tfexec.Terraform` per test config file, but `wd.workDir` set as the working directory. Since we no longer have to symlink the plugin binary itself in `wd.workDir`, we can now just use `wd.configDir` as the Terraform working dir instead.
Provider source files (testdata in directories alongside test source files) must still be symlinked into the Terraform working directory. Since this is now `wd.configDir`, not `wd.workDir`, and each …
> Make binary testing compatible with Terraform 0.15

- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
- internal/plugin/convert/diagnostics.go
- internal/plugin/convert/diagnostics_test.go
When returning Diagnostics, only populate the AttributePath if there are
actually steps. Terraform core has a bug (see hashicorp/terraform#27710)
that will result in any Diagnostic that has an AttributePath with no
steps not being associated with a specific part of the config.
Fixes #561.
> Don't send back empty AttributePaths.

- helper/schema/grpc_provider_test.go
Fix vet errors under Go 1.16 about t.Fatal being called from non-test
goroutines.
> Fix vet errors.

- helper/schema/grpc_provider_test.go
- helper/schema/resource.go
- helper/schema/resource_test.go
Closes #675
(Test changes may be easiest to view with the "hide whitespace changes" option in GitHub as they are just introducing looping to cover relevant Create/CreateContext/CreateWithoutTimeout method implementations.)
The Terraform Plugin SDK has always supported customizable timeouts, declared at the `helper/schema.Resource.Timeouts` level with the operation aware [`helper/schema.ResourceTimeout` type](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceTimeout). These were designed to allow practitioners to implement a timeout per resource, e.g.
```terraform
resource "example_thing" "example" {
timeouts {
create = "60m"
}
}
```
Where the resource logic could fetch the timeout value via [`(helper/schema.ResourceData).Timeout()` …
> helper/schema: Introduce context-aware resource CRUD functions without default timeout

- README.md
- SUPPORT.md
Document that v1-maint is considered deprecated and will EOL on July
31, 2021, and lay out what that means.
> Add information on support policies.

- README.md
- SUPPORT.md
Call out that v2 is generally available and will receive fixes, but that
we don't backport fixes to other minor versions. Generally lay out the
support policy we have been operating with thus far.
> Add SUPPORT.md outlining our support policy.

- .circleci/config.yml
- .github/CONTRIBUTING.md
- README.md
Change all references to "master" to "main" in advance of changing the
default branch on GitHub.
Following merge, we'll use the GitHub functionality to rename the master
branch.
> Rename master branch to main.

- README.md
Fix our README to link to main instead of master for the link that snuck
in after #725 was opened.
> Fix lingering link to master in README.

- internal/plugintest/config.go
I've accidentally made this error a few times, since Go uses these in its .mod file, etc. May be a bit more forgiving for users.
> Allow for "v" prefix in version strings

- go.mod
- go.sum
- helper/schema/grpc_provider.go
- internal/plugin/convert/diagnostics.go
- internal/plugin/convert/diagnostics_test.go
- internal/plugin/convert/schema.go
- internal/plugin/convert/schema_test.go
Upgrade terraform-plugin-go to the unreleased 0.3.0 candidate (still
awaiting merge, so commit hashes won't actually match) and account for
the breaking changes.
This is based off of hashicorp/terraform-plugin-go#74, and we should wait for that to land and be released before merging this.
> Upgrade terraform-plugin-go to 0.3.0 (dev)

- internal/helper/plugin/grpc_provider.go
Our Timeouts code can't handle it yet.
This is a backport of #667.
> [v1] Stop using json.Number when decoding Private.

- helper/schema/schema.go
- helper/schema/schema_test.go
Some of the validation error messages were written with the provider developer audience rather than the end-user audience in mind, and so in helping various folks in the community forum, etc I've occasionally seen folks be confused as to what these messages mean and what to do about them.
The main cases I came here to address were:
* The error messages whose summaries directly mention field names from the `schema.Schema` type, which is not something we expect end-sers to be familiar with.
* The "computed attributes cannot be set" error, because the terminology "computed" doesn't appear in our user-facing documentation. Since we don't actually really _have_ a specific and consistent term for that, rather than introducing one here I instead made it a more plain description of the situation: …
> helper/schema: Adjusted validation error messages

- go.mod
- go.sum
- helper/resource/plugin.go
- helper/resource/testing.go
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
- helper/resource/testing_new_import_state.go
- plugin/debug.go
- plugin/serve.go
In order to support protocol v6 providers in the test suite, we add another
field to `TestCase` along the same lines as `ProtoV5ProviderFactories`. This is
plumbed through as yet another argument in `runProviderCommand`. We hope that by
the time another protocol major version is released, a new, more flexible test
framework will be available.
`plugin.ServeOpts` and `plugin.DebugServe` also expected all provider servers to be
v5 servers, so we also add the `GRPCProviderV6Func` field to `ServeOpts` to keep
it backwards compatible. If both `GRPCProviderFunc` and `GRPCProviderV6Func` are
set, the v6 server will be ignored.
Alternatively, we could panic if both are set.
fixes #737 
needs https://github.com/hashicorp/terraform-exec/pull/182
Tested with terraform-provider-corner at …
> add ProtoV6ProviderFactories to TestCase

- helper/schema/provider.go
- helper/schema/provider_test.go
Closes #790
Previously:
```
--- FAIL: TestProviderConfigure (0.00s)
--- FAIL: TestProviderConfigure/ConfigureContextFunc-warning (0.00s)
/Users/bflad/src/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider_test.go:265: Unexpected diagnostics (-wanted +got):   diag.Diagnostics(
- 	{{Severity: 1, Summary: "Test Warning Diagnostic", Detail: "This is a warning."}},
+ 	nil,
  )
```
> helper/schema: Ensure Provider.ConfigureContextFunc warning-only diagnostics are returned

- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
- helper/schema/resource_data.go
- helper/schema/resource_diff.go
- helper/schema/schema.go
- helper/schema/shims.go
- helper/schema/shims_test.go
- terraform/diff.go
- terraform/state.go
Fixes #793.
We actually create a `terraform.InstanceState` when handling the gRPC methods, and then a ResourceData is created from _that_. So, like with ProviderMeta functionality (#405) we're following the same path and threading our cty values through the instance state.
This still needs unit tests.
> Prototype exposing cty.Values from ResourceData.

- go.mod
- go.sum
- internal/plugintest/config.go
Closes #823
Verification script (ran in terraform-provider-null):
```shell
#!/bin/bash
export TF_ACC=1
export TF_LOG=TRACE
export TF_ACC_LOG_PATH=/tmp/tfacctest.log
ORIGINAL_PATH="${PATH}"
function runtest() {
/bin/rm -f "${TF_ACC_LOG_PATH}"
/usr/local/bin/go test -count=1 ./internal/provider
/usr/bin/grep -E '(Terraform version|CLI args)' "${TF_ACC_LOG_PATH}" | /usr/bin/head -2
echo ""
}
echo ""
echo "==> github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0 <=="
echo ""
echo "Default (no environment variables, terraform on PATH)"
runtest
echo "TF_ACC_TERRAFORM_PATH=/usr/local/bin/terraform0.12.31"
export TF_ACC_TERRAFORM_PATH=/usr/local/bin/terraform0.12.31
runtest
unset TF_ACC_TERRAFORM_PATH
echo "TF_ACC_TERRAFORM_VERSION=0.15.5"
export TF_ACC_TERRAFORM_VERSION=0.15.5
runtest
unset …
```
> internal/plugintest: Migrate from github.com/hashicorp/terraform-exec/tfinstall to github.com/hashicorp/hc-install

- go.mod
- go.sum
- helper/logging/logging.go
- helper/resource/plugin.go
- plugin/serve.go
Upgrade to the latest version of terraform-plugin-go, bringing support
for terraform-plugin-log.
Use the terraform-plugin-log logging sink when setting up the
helper/resource test framework. The idea here is that we'll use the
logging sink to reroute all terraform-plugin-log logs, and leave the
`log.Print` logs the way they are with the existing override. Over time,
it may be nice to migrate those logs to use terraform-plugin-log, which
we've introduced `logging.GetTestLogContext` as a helper for. But that
may be a mistake, and maybe we should wait until we need it to introduce
that function.
In theory, this PR should result in no logs being written to the CLI
during testing, which was happening in hashicorp/terraform-plugin-go#93.
It should respect `TF_LOG` and `TF_LOG_PATH`, as well as …
> Upgrade to latest terraform-plugin-go, add logging sink.

- helper/schema/resource_diff.go
- helper/schema/resource_diff_test.go
Closes #827.
```console
% go test ./helper/schema
ok  	github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema	0.629s
```
> Restore support for empty prefix in `ResourceDiff.GetChangedKeysPrefix`

- go.mod
- go.sum
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
Start using terraform-plugin-log to log SDKv2 level logs, using an
SDKv2-specific subsystem. The environment variable `TF_LOG_SDK_V2`
controls the subsystem's log output.
Fixes #804.
> Add logging using terraform-plugin-log.

- helper/schema/resource_diff.go
- helper/schema/resource_diff_test.go
- helper/schema/schema.go
The following changes will enable shared diff checking functions both during Diff phase and during CRUD operations. Currently, if there is shared logic, the functions look similar to (from https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_lambda_function.go):
```go
type resourceDiffer interface {
HasChange(string) bool
}
func needsFunctionCodeUpdate(d resourceDiffer) bool {
return d.HasChange("filename") || d.HasChange("source_code_hash") || d.HasChange("s3_bucket") || d.HasChange("s3_key") || d.HasChange("s3_object_version")
}
func updateComputedAttributesOnPublish(_ context.Context, d *schema.ResourceDiff, meta interface{}) error {
if needsFunctionCodeUpdate(d) {
...
}
}
func resourceAwsLambdaFunctionUpdate(d *schema.ResourceData, meta …
```
> Adds HasChanges() to ResourceDiff

- go.mod
- go.sum
- helper/resource/testing_new_test.go
- internal/configs/hcl2shim/flatmap_test.go
- tools/tools.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/pull/851
Reference: https://github.com/hashicorp/terraform-plugin-sdk/pull/849
The `mockgen` command is not used in this repository and likely was a vestiage of splitting this repository from github.com/hashicorp/terraform.
This repository (and many of the other Terraform Plugin repositories) overwhelmingly use `go-cmp` instead of `deep`. The three usages are migrated for consistency and to remove this dependency.
> deps: Remove github.com/golang/mock and github.com/go-test/deep

- helper/schema/schema.go
add docs on why old might be empty in diffsuppressfunc
> add docs on why old might be empty in diffsuppressfunc

- .golangci.yml
- helper/customdiff/computed.go
- helper/customdiff/force_new.go
- helper/logging/transport.go
- helper/resource/state_shim.go
- helper/schema/field_writer_map.go
- helper/schema/grpc_provider_test.go
- helper/schema/resource_diff_test.go
- helper/schema/resource_test.go
- helper/schema/schema_test.go
- helper/schema/shims_test.go
- internal/plugintest/working_dir.go
Previously:
```text
helper/logging/transport.go:55:15: Error return value of `json.Indent` is not checked (errcheck)
json.Indent(&out, b, "", " ")
^
internal/plugintest/working_dir.go:103:19: Error return value of `wd.tf.SetLogPath` is not checked (errcheck)
wd.tf.SetLogPath(p)
^
helper/customdiff/computed.go:14:20: Error return value of `d.SetNewComputed` is not checked (errcheck)
d.SetNewComputed(key)
^
helper/customdiff/force_new.go:18:14: Error return value of `d.ForceNew` is not checked (errcheck)
d.ForceNew(key)
^
helper/customdiff/force_new.go:38:14: Error return value of `d.ForceNew` is not checked (errcheck)
d.ForceNew(key)
^
helper/resource/state_shim.go:238:13: Error return value of `sf.AddEntry` is not …
```
> Enable errcheck linter and fix issues

- .golangci.yml
- helper/schema/field_reader_config.go
- helper/schema/field_reader_diff.go
- helper/schema/field_reader_map.go
- helper/schema/grpc_provider.go
The field reader/writing handling of this codebase is generally considered frozen, but we want to catch and fix other potential `nilerr` issues.
Previously:
```text
helper/schema/field_reader_config.go:206:3: error is not nil (line 204) but it returns nil (nilerr)
return FieldReadResult{}, nil
^
helper/schema/field_reader_diff.go:131:3: error is not nil (line 129) but it returns nil (nilerr)
return FieldReadResult{}, nil
^
helper/schema/field_reader_map.go:66:3: error is not nil (line 64) but it returns nil (nilerr)
return FieldReadResult{}, nil
^
helper/schema/grpc_provider.go:199:3: error is not nil (line 139) but it returns nil (nilerr)
return resp, nil
^
```
> Enable nilerr linter and fix issues

- .golangci.yml
- helper/resource/testing.go
- helper/resource/testing_test.go
- helper/schema/field_reader.go
- helper/schema/field_reader_config.go
- helper/schema/field_reader_config_test.go
- helper/schema/field_reader_diff.go
- helper/schema/field_reader_map.go
- helper/schema/field_writer_map.go
- helper/schema/grpc_provider.go
- helper/schema/resource.go
- helper/schema/resource_diff_test.go
- helper/schema/resource_test.go
- terraform/state.go
To reduce potential confusion caused by function signatures.
Previously:
```text
terraform/state.go:387:30: `(*State).removeModule` - `path` is unused (unparam)
func (s *State) removeModule(path []string, v *ModuleState) {
^
terraform/state.go:415:32: `(*State).removeInstance` - `path` is unused (unparam)
func (s *State) removeInstance(path []string, r *ResourceState, v *InstanceState) {
^
helper/resource/testing.go:549:58: Test$1 - result 1 (error) is always nil (unparam)
c.ProviderFactories[name] = func() (*schema.Provider, error) {
^
helper/resource/testing.go:1007:33: `modulePrimaryInstanceState` - `s` is unused (unparam)
func modulePrimaryInstanceState(s *terraform.State, ms *terraform.ModuleState, name string) …
```
> Enable unparam linter and fix issues

- .golangci.yml
- helper/acctest/random.go
- helper/customdiff/computed_test.go
- helper/customdiff/condition.go
- helper/customdiff/condition_test.go
- helper/customdiff/force_new.go
- helper/customdiff/force_new_test.go
- helper/customdiff/testing_test.go
- helper/customdiff/validate.go
- helper/customdiff/validate_test.go
- helper/resource/testing_new_import_state.go
- helper/schema/resource_diff.go
- helper/schema/resource_timeout_test.go
- helper/schema/schema.go
- helper/schema/schema_test.go
- helper/structure/suppress_json_diff.go
- helper/structure/suppress_json_diff_test.go
- helper/validation/map.go
- internal/configs/hcl2shim/flatmap.go
- terraform/resource.go
- terraform/resource_test.go
- terraform/state.go
Shadowing language keywords can cause confusing programming issues and may not provide enough clarity on the purpose of a variable.
Previously:
```text
helper/acctest/random.go:123:5: variable len has same name as predeclared identifier (predeclared)
if len := r.BitLen(); len > 31 {
^
helper/customdiff/condition.go:15:62: param new has same name as predeclared identifier (predeclared)
type ValueChangeConditionFunc func(ctx context.Context, old, new, meta interface{}) bool
^
helper/customdiff/condition.go:44:8: variable new has same name as predeclared identifier (predeclared)
old, new := d.GetChange(key)
^
helper/customdiff/force_new.go:39:8: variable new has same name as predeclared identifier (predeclared)
old, new …
```
> Enable predeclared linter and fix issues

- helper/schema/provider.go
- helper/schema/provider_test.go
Closes #877
Ideally, this method would've been updated to use and return diagnostics in addition to the new error handling, however its signature is protected by major version compatibility guarantees.
> helper/schema: Update misleading error messaging during import

- .golangci.yml
- helper/resource/testing.go
- helper/schema/field_reader_map.go
- helper/schema/resource.go
- helper/schema/set.go
- helper/validation/float_test.go
- helper/validation/int_test.go
- helper/validation/meta_test.go
- helper/validation/strings_test.go
- internal/addrs/module_instance.go
- internal/plugin/convert/diagnostics.go
- terraform/state.go
Previously:
```text
helper/validation/float_test.go:66:17: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
expectedErr: regexp.MustCompile("expected [\\w]+ to be at least \\(2\\.5\\d*\\), got 1\\.5\\d*"),
^
helper/validation/float_test.go:71:17: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
expectedErr: regexp.MustCompile("expected type of [\\w]+ to be float"),
^
helper/validation/float_test.go:89:17: S1007: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (gosimple)
expectedErr: regexp.MustCompile("expected [\\w]+ to be at most \\(1\\.5\\d*\\), got 2\\.5\\d*"),
^ …
```
> Enable gosimple linter and fix issues

- .golangci.yml
- terraform/state_filter.go
Previously:
```text
terraform/state_filter.go:39:8: append to slice `as` with non-zero initialized length (makezero)
as = append(as, &resourceAddress{Index: -1})
^
```
> Enable makezero linter and fix issue

- .golangci.yml
- helper/schema/grpc_provider.go
- helper/schema/provider.go
- helper/schema/resource.go
- helper/schema/resource_data.go
- helper/schema/schema.go
- internal/logging/context.go
- internal/logging/environment_variables.go
- internal/logging/helper_schema.go
- internal/logging/keys.go
- internal/plugintest/util.go
Reference: https://github.com/hashicorp/terraform-plugin-go/tree/main/internal/logging
The majority of these issues were in the gRPC server handling for some recent inclusion of logging that did not include other context handling. This adds some logic handoff trace logs to the helper/schema logger and starts an internal logging package, similar to the terraform-plugin-go implementation.
Previously:
```text
internal/plugintest/util.go:13:4: ineffectual assignment to err (ineffassign)
err = os.Chmod(dest, srcInfo.Mode())
^
helper/schema/grpc_provider.go:75:2: ineffectual assignment to ctx (ineffassign)
ctx = withLogger(ctx)
^
helper/schema/grpc_provider.go:126:2: ineffectual assignment to ctx (ineffassign)
ctx = …
```
> Enable ineffassign linter and fix issues

- .changelog/857.txt
- .github/dependabot.yml
- go.mod
- plugin/debug.go
- plugin/serve.go
Closes #650 
Providers will automatically receive upstream enhancements to provider servers, including protocol logging and the increased gRPC message limit. Lower level dependencies in this SDK, such as gRPC and go-plugin versions, can instead be managed upstream, which will ensure consistency across the SDKs.
> plugin: Serve via tf5server/tf6server rather than go-plugin directly

- .golangci.yml
- helper/resource/testing_new_import_state.go
- helper/schema/resource_timeout.go
- helper/schema/schema_test.go
- helper/schema/shims_test.go
- helper/validation/strings.go
- internal/plugintest/working_dir.go
- terraform/state.go
Closes #865
Reference: https://www.terraform.io/language/settings/backends/local#path
The removal of the deprecated `refresh` command `-state` flag in the acceptance testing framework should be safe as this is the default state location.
Previously:
```
internal/plugintest/working_dir.go:246:79: SA1019: tfexec.State is deprecated: The -state CLI flag is a legacy flag and should not be used. If you need a different state file for every run, you can instead use the local backend. See https://github.com/hashicorp/terraform/issues/25920#issuecomment-676560799 (staticcheck)
return wd.tf.Refresh(context.Background(), tfexec.Reattach(wd.reattachInfo), tfexec.State(filepath.Join(wd.baseDir, "terraform.tfstate")))
^
helper/schema/schema_test.go:3091:63: SA4009: argument v is overwritten before …
```
> Enable staticcheck linter and fix issues

- helper/resource/environment_variables.go
- helper/resource/plugin.go
- helper/resource/testing.go
- helper/resource/testing_test.go
- internal/plugintest/config.go
- internal/plugintest/environment_variables.go
- internal/plugintest/guard.go
- internal/plugintest/helper.go
- internal/plugintest/working_dir.go
Closes #830
This also removes two unused internal functions from the internal/plugintest package.
The missing terraform.io website documentation for this environment variable will be separately submitted as well.
> helper/resource: Additional Go documentation for acceptance testing environment variables and CLI installation behaviors

- .changelog/891.txt
- helper/logging/logging.go
- helper/resource/plugin.go
- helper/resource/testing.go
- helper/resource/testing_config.go
- helper/resource/testing_new.go
- helper/resource/testing_new_config.go
- helper/resource/testing_new_import_state.go
- internal/logging/context.go
- internal/logging/environment_variables.go
- internal/logging/helper_resource.go
- internal/logging/keys.go
- internal/plugintest/config.go
- internal/plugintest/helper.go
- internal/plugintest/working_dir.go
Closes #838
This new subsystem logger is meant for instrumenting the acceptance testing framework. Most of the changes are to support passing the context to many of the functions and adding `DEBUG`/`TRACE` log entries for provider developer and SDK maintainer troubleshooting.
Verified `go test` logging behaviors via terraform-provider-corner:
- No logs by default
- `TF_LOG_SDK_HELPER_RESOURCE` environment variable control of new logger
- `TF_LOG` enabling new logger
- `TF_ACC_LOG_PATH` enabling new logger
> helper/resource: Added terraform-plugin-log logger and extensive log entries

- .github/workflows/ci-go.yml
- helper/resource/plugin.go
- helper/resource/testing_new.go
- internal/logging/keys.go
- internal/plugintest/working_dir.go
- plugin/serve.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/pull/857
Replicating the `tf5server` close channel handling right above it -- it was a copy-paste miss on my part. Without this, `tf6server` (such as terraform-plugin-framework providers) will hang until test timeouts. This hasn't been released yet, so does not require a CHANGELOG entry, but it is a blocker for releasing 2.11.0.
As part of troubleshooting this, was able to add some helpful trace and debug logging for future travelers.
> plugin: Always forward tf6server close channel

- helper/resource/testing.go
- internal/plugintest/working_dir.go
- internal/plugintest/working_dir_json_test.go
This implements the proposal described in https://github.com/hashicorp/terraform-plugin-sdk/issues/721
The exported [plugintest.WorkingDir.SetConfig](
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/internal/plugintest#WorkingDir.SetConfig
) API was deliberately left unmodified to avoid a breaking change.
The only possible breaking change is the [mid-struct addition](
https://github.com/hashicorp/terraform-plugin-sdk/compare/master...rudo-thomas:support-json-syntax-in-tests?expand=1#diff-ef6290017990b7efb9ea81ebcad8974eb0a441f9f2adca610f403dbd32ea5619R405
) of the `ConfigIsJSON` field to `TestStep` which could break users that initialise the structure without using the the _Field_: syntax. Such uses are very unlikely, as the structure had 19 fields already, 20 with …
> Support testing of configurations in JSON syntax.

- helper/schema/resource.go
- helper/schema/schema.go
Closes #467
Closes #601
Closes #705 
Closes #735
This also spends some cycles fixing the Go documentation for struct fields to be aligned with each field individually, so pkg.go.dev and the Go language server can appropriately show the matching documentation.
> helper/schema: Additional Go documentation for Resource and Schema types

- helper/resource/testing.go
- helper/resource/testing_example_test.go
> helper/resource: Additional Go documentation for TestCheck and TestMatch functions

- helper/schema/schema.go
- helper/schema/schema_test.go
This brings the int field up to par with bool and float ones.
Fixes https://github.com/hashicorp/terraform-plugin-sdk/issues/773
> helper/schema: Make int fields accept string values from DefaultFunc().

- helper/resource/testing_sets.go
- helper/resource/testing_sets_example_test.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/pull/911
Additional glow up for the `TypeSet` functions, similar to the others.
> helper/resource: Additional Go documentation for TypeSet TestCheckFunc

- internal/plugintest/config.go
Context: #923, https://github.com/hashicorp/terraform-plugin-sdk/issues/923#issuecomment-1087398496
With this change I'm addressing ~~2~~ 1 issue~~s~~:
1. make sure that when we call [hc-install](https://github.com/hashicorp/hc-install) `installer.Ensure`, we contextualise the error a bit. Admittedly, `hc-install` errors should be a bit more verbose too.
~~2. avoid pointless "work" by making sure the calls to `DiscoverConfig` are cached and serialized with a `sync.Mutex`. Given a specific `sourceDir`, the discovery should happen only once, even when highly parallel testing is applied~~
After talking with @bflad I understand that the way the tests get setup by the SDK prevent that 2 installations of Terraform might be happening in the same directory. This renders my whole "add a critical …
> Improve error reporting and avoid repeating `DiscoveryConfig` when unnecessary in `plugintest`

- helper/resource/testing_new.go
The "unsupported test mode" message does not tell you which step of the test failed, unlike the other fatal errors in the `runNewTest` function here. This change adds the step number to the error message to make it more useful and more consistent.
> Improve "unsupported test mode" message

- helper/resource/plugin.go
- helper/schema/grpc_provider.go
- helper/schema/provider.go
- helper/schema/resource.go
- helper/schema/resource_diff_test.go
- helper/schema/schema.go
- internal/logging/helper_schema.go
- internal/plugin/convert/schema.go
- internal/plugin/convert/schema_test.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/issues/863
By default, the standard library `log` package will include the short timestamp and date flags, which when output will prefix any messaging, e.g.
```text
2022/01/26 16:25:33 [DEBUG] Test message
```
When a provider is running in production and the log output is being sent across the go-plugin boundary, Terraform CLI generally expects a hc-log formatted entry (square bracket log level prefixed message) or will output the raw message. So in many cases, this class of logging shows up in production logs as the raw message and the log level is not recognized, which is confusing for practitioners and provider developers:
```text
2022-01-26T16:25:33.123-0800 [INFO] provider.terraform-provider-example_v9.9.9_x5: 2022/01/26 …
```
> all: Replace various log.Printf calls with tfsdklog calls

- .changelog/950.txt
- helper/resource/testing.go
- helper/resource/testing_example_test.go
- helper/resource/testing_test.go
> Adding `resource.TestCheckResourceAttrWith` test utility

- .changelog/983.txt
- helper/resource/testing.go
If the sweeper framework returns an error, such as a missing sweeper dependency, the error is not displayed to the user.
```
...
2022/06/14 13:06:18 [DEBUG] Sweeper (aws_redshift_scheduled_action) already ran in region (us-west-2)
FAIL	github.com/hashicorp/terraform-provider-aws/internal/sweep	58.064s
FAIL
make: *** [sweep] Error 1
```
Now logs the error
```
...
2022/06/14 14:21:45 [DEBUG] Sweeper (aws_appconfig_configuration_profile) already ran in region (us-west-2)
2022/06/14 14:21:45 [ERROR] Sweeper (aws_docdb_global_cluster) has dependency (aws_docdb_cluster), but that sweeper was not found
FAIL	github.com/hashicorp/terraform-provider-aws/internal/sweep	60.860s
FAIL
make: *** [sweep] Error 1
```
> Add final sweeper error to logs

- website/docs/plugin/sdkv2/index.mdx
Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/368
Provider developers no longer need to use the terraform-plugin-mux `tf6to5server` package when combining sdk/v2 and framework providers with Terraform 0.12 and later compatibility.
> website: Clarify migration steps now that framework supports protocol version 5

- .changelog/993.txt
- .changelog/pending.txt
- internal/logging/keys.go
- internal/plugintest/environment_variables.go
- internal/plugintest/helper.go
- website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
Closes #992
This enables provider developers to have full control over Terraform CLI logging environment variables with the acceptance testing framework in `helper/resource`.
In Terraform CLI 0.15 and later, the logging environment variables work as the following:
| Environment Variable | Description |
| - | - |
| `TF_LOG` | Global logging level for core and providers. Overrides `TF_LOG_CORE` (but not `TF_LOG_PROVIDER`) if set. |
| `TF_LOG_CORE` |  Logging level for core functionality. No effect if `TF_LOG` is set. |
| `TF_LOG_PROVIDER` | Logging level for provider logging sent over plugin file descriptors. |
To execute Terraform CLI during acceptance testing, it uses `terraform-exec` for all interactions. `terraform-exec` has certain environment variable handling rules associated with …
> helper/resource: Add `TF_ACC_LOG`, `TF_LOG_CORE`, and `TF_LOG_PROVIDER` environment variable handling for Terraform versions 0.15 and later

- website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
> website: Documentation for parallel logging issues with TF_LOG_PATH_MASK

- .changelog/1006.txt
- .github/workflows/ci-go.yml
- .gitignore
- Makefile
- go.mod
- go.sum
- helper/logging/logging_http_transport.go
- helper/logging/logging_http_transport_test.go
- helper/logging/transport.go
- helper/schema/provider_test.go
Related: https://github.com/hashicorp/terraform-provider-tfe/pull/479
Related: #2 
Closes: #546
Current SDK offers an helper `http.RoundTripper` in `helpers/logging`, that is created via `logging.NewTransport()`. This `http.RountTripper` can then be used as `.Transport` in an `http.Client`.
When logging level is _debug or higher_, it does a simple dump of the whole content of the request and of the following response.
This exposes any sensitive information that might be going over HTTP, and there is no way for developers using this code, to setup any filtering.
This PR introduced a 2 new implementations of `http.RoundTripper`, one designed to log via the provider root logger, the other via a user-defined subsystem.
```golang
func NewLoggingHTTPTransport(t http.RoundTripper) …
```
> Introduce `NewLoggingHTTPTransport` and deprecate `NewTransport`

- helper/schema/schema.go
- website/docs/plugin/sdkv2/schemas/schema-methods.mdx
> helper/schema: Clarify Schema type Deprecated field usage

- website/data/plugin-sdk-nav-data.json
- website/docs/plugin/sdkv2/logging/http-transport.mdx
This adjusts the side navigation so Logging and Testing are more prominent and close to Debugging, which are similar in nature.
> website: Logging navigation adjustments, minor HTTP Transport page fixes

- website/docs/plugin/sdkv2/best-practices/deprecations.mdx
- website/docs/plugin/sdkv2/best-practices/detecting-drift.mdx
- website/docs/plugin/sdkv2/guides/terraform-0.12-compatibility.mdx
- website/docs/plugin/sdkv2/guides/v2-upgrade-guide.mdx
- website/docs/plugin/sdkv2/logging/http-transport.mdx
- website/docs/plugin/sdkv2/resources/customizing-differences.mdx
- website/docs/plugin/sdkv2/resources/import.mdx
- website/docs/plugin/sdkv2/resources/retries-and-customizable-timeouts.mdx
- website/docs/plugin/sdkv2/resources/state-migration.mdx
- website/docs/plugin/sdkv2/schemas/schema-behaviors.mdx
- website/docs/plugin/sdkv2/schemas/schema-methods.mdx
- website/docs/plugin/sdkv2/schemas/schema-types.mdx
- website/docs/plugin/sdkv2/testing/acceptance-tests/sweepers.mdx
Closes #834
Updates the website documentation to use Go 1.18+ `any` instead of an empty interface (`interface{}`) as the latter can be confusing to those unfamiliar with Go.
Code updates within this Go module can be refactored at some other point, if necessary or desired.
> website: Replace interface{} with any

- helper/schema/schema.go
I was trying to model a block that had `map[string][]string` as it's schema, but the code was panicking with:
```
Unknown validation type: 6
```
Debugging, and it became clear that non-primitive types are not supported in the switch, but I was puzzled as to why it was reporting that a `TypeMap` was not a valid map value.
The switch is against `valueType`, so it makes sense (to me at least) that the panic should report that as the unknown validation type.
With this change, the code would report:
```
Unknown validation type: 7
```
Where 7 equates to `TypeSet` (aka. the string slice value of the map)
> Fix panic message to show correct unhandled type rather than the parent type

- helper/customdiff/compose.go
- website/docs/plugin/sdkv2/resources/customizing-differences.mdx
These functions all take a `context.Context` as their first argument now.
https://github.com/hashicorp/terraform-plugin-sdk/blob/9bdb216a4ab835003a624b0a15ac39c58ef2861e/helper/customdiff/validate.go#L12
https://github.com/hashicorp/terraform-plugin-sdk/blob/2f7133b9729bf59bd8a59e006f15e4f845556284/helper/customdiff/condition.go#L15
https://github.com/hashicorp/terraform-plugin-sdk/blob/2f7133b9729bf59bd8a59e006f15e4f845556284/helper/customdiff/condition.go#L11
> docs: customdiff.{ValidateChange,ForceNewIfChange,ComputedIf} take a context.Context

- helper/schema/schema.go
- helper/schema/schema_test.go
This PR adds the resource path to error messages when a list type either has too many or too few elements.
> fix: add path to error when list has too many or few items

- helper/logging/logging_http_transport_test.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/actions/runs/2970165412
Previously:
```
--- FAIL: TestNewLoggingHTTPTransport (0.27s)
/Users/bflad/src/github.com/hashicorp/terraform-plugin-sdk/helper/logging/logging_http_transport_test.go:93: Unexpected value for field "Content-Type"; expected "text/html", got "text/html; charset=utf-8"
```
Double checking the current situation with `curl`:
```console
$ curl -I -s https://www.terraform.io | grep -i content-type
content-type: text/html; charset=utf-8
```
> helper/logging: Update test Content-Type header to match terraform.io change

- website/data/plugin-sdk-nav-data.json
The DevDot process flagged two issues with the sidebar:
- The logging pages that are actually links to an entire other docs section (but this isn't necessarily obvious to users before they click them)
- The link to learn tutorials. We don't need this anymore! tutorials will be integrated into devdot.
This PR removes the learn link and limits the logging section to one pointer page and the page about HTTP transport. These pages DO exist in this documentation set but then points users to the external logging documentation set. I think this is a happy medium that will get users where they need to go, let them know logging stuff exists, but not provide unexpected links to another doc set.
> Updating Sidebar to Match Design Spec

- internal/plugintest/util.go
Reference: https://pkg.go.dev/os#File.Readdir
Reference: https://pkg.go.dev/os#ReadDir
While attempting to troubleshoot macOS kernel panic behaviors while running acceptance testing, I was able to capture a log whose last entry was `Symlinking source directories to work directory`. Since that operation tends to occur in temporary directory space, there is at least some potential there for strange macOS and Go behaviors.
The `(os.File).Readdir()` method does make this mention in particular:
> Most clients are better served by the more efficient ReadDir method.
Making this a branch so others potentially affected by macOS kernel panics can try this out. This may not be the root cause, as there is a lot more process-oriented logic that occurs to start and stop providers in the testing …
> internal/plugintest: Switch from (os.File).Readdir() to os.ReadDir()

- .changelog/1077.txt
- helper/resource/testing_new_import_state.go
- helper/resource/teststep_providers_test.go
References: #1074 
Closes: #1066 
Closes: #1074 
~~Changes in this PR are to accompany changes in #1074.
@gdavison feel free to pull these changes into your PR and we can merge it all in together.~~
~~Tests in this PR fail as expected, require changes in #1074 to pass.~~
I've cherry-picked @gdavison's changes from #1074 into this PR.
> Adding test coverage for changes to ignore data sources in imported state

- helper/logging/logging.go
- helper/resource/plugin.go
- internal/plugintest/config.go
- internal/plugintest/helper.go
- internal/plugintest/working_dir.go
Previously (locally for me):
```
internal/plugintest/config.go:6:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
"io/ioutil"
^
internal/plugintest/helper.go:7:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
"io/ioutil"
^
internal/plugintest/working_dir.go:8:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now …
```
> all: Remove deprecated io/ioutil package usage

- website/data/plugin-sdk-nav-data.json
- website/docs/plugin/sdkv2/index.mdx
> Linking to the framework migration guide

- go.mod
- go.sum
- helper/resource/testing_new.go
- helper/resource/testing_new_import_state.go
- helper/resource/testing_new_import_state_test.go
- helper/resource/testing_new_refresh_state.go
- helper/schema/resource_diff_test.go
- internal/configs/configschema/coerce_value_test.go
- internal/configs/configschema/empty_value_test.go
- internal/plans/objchange/normalize_obj_test.go
- terraform/state_test.go
Removes some additional, mainly testing-related dependencies to further reduce maintenance and code migration burden of this Go module. The only external facing change is the output of ImportStateVerify and (very uncommon, not recommended) IDRefreshName differences, which feel slightly cleaner with the standard go-cmp output.
Prior:
```
--- FAIL: TestTest_TestStep_ImportStateVerify (0.83s)
/Users/bflad/src/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_import_state_test.go:87: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=1) {
(string) (len=11) "create_only": (string) (len=9) "testvalue"
}
FAIL
FAIL …
```
> deps: Remove github.com/apparentlymart/go-dump and github.com/davecgh/go-spew

- .github/workflows/issue-comment-created.yml
Reference: https://github.com/hashicorp/terraform-plugin-sdk/labels/waiting-response
The `stale` label is there should we ever want to use actions/stale (similar to other HashiCorp projects).
> .github/workflows: Fix label name in issue comment workflow

- .changes/unreleased/BUG FIXES-20230213-150146.yaml
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
Closes #1145
Reference: https://github.com/hashicorp/terraform/pull/32463
Terraform 1.3.8 and later now correctly handles null values for single nested blocks. This means Terraform will now report differences between a null block and known block with null values. This SDK only supported single nested blocks via its timeouts functionality.
This change is a very targeted removal of any potential `timeouts` block values in a resource state from the `ImportResourceState` RPC. Since configuration is not available during that RPC, it is never valid to return any data beyond null for that block. This will prevent unexpected differences on the first plan after import, where Terraform will report the block removal for configurations which do not contain the block.
New unit test failure prior to …
> helper/schema: Remove timeouts during ImportResourceState

- website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
- website/docs/plugin/sdkv2/testing/acceptance-tests/sweepers.mdx
- website/docs/plugin/sdkv2/testing/acceptance-tests/testcase.mdx
- website/docs/plugin/sdkv2/testing/acceptance-tests/teststep.mdx
- website/docs/plugin/sdkv2/testing/index.mdx
- website/docs/plugin/sdkv2/testing/unit-testing.mdx
Reference: https://discuss.hashicorp.com/t/announcing-the-terraform-plugin-testing-module/49914
This renders as an informational callout at the top of each of the existing SDKv2 testing pages to encourage migrating to the new testing module.
> website: Add highlight callout for migrating to terraform-plugin-testing

- go.mod
- go.sum
- helper/resource/testing_new_config_test.go
- helper/resource/testing_new_import_state_test.go
A recent update of `tfexec` [v0.18.0](https://github.com/hashicorp/terraform-exec/releases/tag/v0.18.0) caused a regression where detailed stderr information wasn't being passed to downstream modules. This has now been fixed with the new release [v0.18.1](https://github.com/hashicorp/terraform-exec/releases/tag/v0.18.1)
- Added tests for ExpectError, so future CI can catch bugs similar to the one introduced in #1154  
- Backported from https://github.com/hashicorp/terraform-plugin-testing/pull/86
- Example of new tests [failing](https://github.com/hashicorp/terraform-plugin-sdk/actions/runs/4304693483/jobs/7506075777#step:5:80) w/ tfexec `v0.18.0`
> Bump `terraform-exec` to `v0.18.1`

- .changes/unreleased/NOTES-20230303-111728.yaml
- .github/workflows/ci-go.yml
- README.md
- go.mod
- website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
> Updating to Go 1.19

- helper/acctest/random.go
Closes #621
Similar to `RandSSHKeyPair`, whose cryptographic characteristics were recently more documented, the `RandTLSCert` helper was created with limited customization capabilities. Security requirements are constantly evolving and it is untenable for this Go module to maintain all possible permutations required for cryptographic logic needed across the entire provider ecosystem without constant maintenance or inevitably needing to introduce breaking changes to the exported Go APIs. Future major versions of this code would likely remove helpers like these for that reason, but any decision in that regard would happen at a later date. For now, this documentation will encourage developers to create their own functionality using the Go language standard library `crypto` package if their …
> helper/acctest: Further document RandTLSCert characteristics

- .changes/unreleased/BUG FIXES-20230321-085655.yaml
- helper/resource/aliases.go
> helper/resource: Add missing equals for type aliases

- helper/schema/schema.go
Closes #1185
While the intention of the Go documentation matches Terraform's expectations, other parts of the SDK explicitly validate against the schema definition it was recommending. This documentation change is safer than trying to reconcile all the potential behavior changes should this particular validation be removed and a developer attempts to set `Computed`.
> helper/schema: Remove Default mention from Schema type Optional field Go documentation

- helper/validation/network.go
The old error was misleading for users, as IPv6 CIDR are valid
> helper/validation: clarify IsCIDR() error message

- .changes/unreleased/ENHANCEMENTS-20230623-102412.yaml
- .changes/unreleased/NOTES-20230623-102528.yaml
- helper/schema/core_schema.go
- helper/schema/field_reader.go
- helper/schema/field_reader_config.go
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
- helper/schema/resource.go
- helper/schema/resource_test.go
- helper/schema/schema.go
- helper/schema/serialize.go
- helper/schema/shims.go
Closes #1217
This change introduces a new `SchemaFunc` field and `SchemaMap` method to the `Resource` type. Currently, the `Schema` field data of all `Resource` is held in memory for the lifecycle of the provider server, which is problematic for providers with many resources and/or larger schemas in resources. The new field enables provider developers to swap pieces of resident memory usage for the slight additional computation time of reconstituting the data when necessary.
Callers directly referencing the exported `Schema` field should switch to referencing the `SchemaMap` method, which returns the result of `SchemaFunc` or `Schema` in that preference order. To ensure internal usage was migrated to the new method, this change was performed by temporarily commenting out the `Schema` …
> helper/schema: Add SchemaFunc field to Resource type

- .golangci.yml
- helper/logging/logging_http_transport_test.go
Originally found in #1223 - The unit test `TestNewLoggingHTTPTransport_LogMasking` started failing in a recent dependabot PR: https://github.com/hashicorp/terraform-plugin-sdk/actions/runs/5473296958/jobs/10006381743?pr=1223
The test failing is using a `GET https://www.terraform.io` request to test the masking for the logger on the response body, using a regex `<html>.*</html>` for the mask. I believe the site must have changed recently and introduced some `\n` characters, because `.` in RE2 regex does not match `\n` characters by default: https://github.com/google/re2/blob/a57a1d6462a1613e5e2cfd6fb1ce26d36706a9af/doc/syntax.txt#L68
Adjusting the test's regex to include that flag should fix it -> `(?s)<html>.*</html>`
- Added timeout for lint
> helper/logging: Adjust unit test regex flag

- .changes/unreleased/ENHANCEMENTS-20230808-111940.yaml
- .changes/unreleased/ENHANCEMENTS-20230808-111941.yaml
- .changes/unreleased/NOTES-20230808-103724.yaml
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
- helper/schema/resource.go
- website/data/plugin-sdkv2-nav-data.json
- website/docs/plugin/sdkv2/resources/data-consistency-errors.mdx
- website/docs/plugin/sdkv2/resources/index.mdx
Closes #1227
Introduces new `Resource` type `EnableLegacyTypeSystemApplyErrors` and `EnableLegacyTypeSystemPlanErrors` fields that prevent the `PlanResourceChange` and `ApplyResourceChange` protocol operation responses from setting the `UnsafeLegacyTypeSystem` flag. When Terraform encounters the `UnsafeLegacyTypeSystem` flag, it will demote certain data consistency issues from error diagnostics that would immediately prevent Terraform workflows from completing to warning logs, which can be difficult for provider developers to discover. Provider developers are not  generally expected to try enabling these settings unless discovering these data consistency issues upfront is desired before migrating resources to terraform-plugin-framework.
This setting is on the individual resource level …
> helper/schema: Add `Resource` type flags for disabling legacy type system protocol flags

- .changes/unreleased/ENHANCEMENTS-20230222-001027.yaml
- helper/validation/meta.go
- helper/validation/meta_test.go
- helper/validation/testing.go
> Add `AllDiag` and `AnyDiag` to helper/validation for combining `SchemaValidateDiagFunc`

- .changes/unreleased/ENHANCEMENTS-20230829-141309.yaml
- helper/validation/strings.go
- helper/validation/strings_test.go
The validation function's error is ambiguous when dealing with slices containing spaces. For example:
```
expected role_name to be one of [Apache Spark Administrator Synapse Credential User Synapse Administrator]
```
By changing the format verb, the error becomes more user friendly:
```
expected role_name to be one of ["Apache Spark Administrator" "Synapse Credential User" "Synapse Administrator"]
```
This fixes #464
> helper/validation: `StringInSlice`: Single quote slice elements

- .changes/unreleased/NOTES-20230906-055849.yaml
- .github/workflows/ci-go.yml
- README.md
- go.mod
- helper/acctest/random.go
- tools/go.mod
- website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
> all: Update Go Module to Go 1.20

- go.mod
- helper/customdiff/compose.go
- helper/customdiff/compose_test.go
- helper/resource/testing.go
- helper/resource/testing_test.go
- helper/schema/provider.go
- internal/diagutils/diagutils.go
- terraform/state.go
Reference: https://github.com/hashicorp/terraform-plugin-testing/issues/99
Similar to terraform-plugin-testing, now that this Go module is Go 1.20+, we can use native `errors.Join()` functionality for joining multiple errors.
To fully remove the dependency, will need to update some other dependencies as well, e.g.
```
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugintest
github.com/hashicorp/hc-install
github.com/hashicorp/go-multierror
```
> deps: Remove github.com/hashicorp/go-multierror direct dependency

- website/docs/plugin/sdkv2/testing/unit-testing.mdx
The included example hasnt been updated since the code reorganization which includes the exporting of the Flatten function. Trying to figure it out took me a couple minutes... figured it might be helpful to someone to just update the docs
> Update unit test doc example in AWS provider

- .changes/unreleased/NOTES-20231011-094644.yaml
Previously:
```
Error: unmarshaling change file '.changes/unreleased/NOTES-20231011-094644.yaml': yaml: line 2: did not find expected key
```
Created separate internal issue to catch this during PRs.
> changelog: Fix entry quoting issues

- .github/workflows/release.yml
- meta/meta.go
The new meta-version job in the release process was not using the latest branch reference for checkout (similar to release-tag). This fixes the release workflow and resets the meta version to re-run release.
Previously:
```
To https://github.com/hashicorp/terraform-plugin-sdk.git
! [rejected]          main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/hashicorp/terraform-plugin-sdk.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
```
> .github: Ensure new meta-version release job uses latest branch reference

- .changes/unreleased/NOTES-20240129-084840.yaml
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
Reference: https://github.com/hashicorp/terraform-plugin-go/pull/351
Reference: https://developer.hashicorp.com/terraform/plugin/framework/migrating
The next versions of the plugin protocol (5.5/6.5) include support for moving resource state across resource types. The terraform-plugin-sdk Go module will not be receiving this feature, however this Go module must be updated to handle the new RPC with errors.
Provider developers can implement move resource state in their terraform-plugin-sdk based providers by following the framework migration documentation to introduce terraform-plugin-mux and migrating the resource type to terraform-plugin-framework.
> all: Initial MoveResourceState implementation

- website/docs/plugin/sdkv2/resources/data-consistency-errors.mdx
Corrects `EnableLegacyTypeSystem<Operation>Errors` constants in documentation
> Corrects `EnableLegacyTypeSystem<Operation>Errors` constants

- .changes/unreleased/NOTES-20240906-171344.yaml
- .github/workflows/ci-go.yml
- README.md
- go.mod
- tools/go.mod
Ref: https://github.com/hashicorp/terraform-providers-devex-internal/issues/182
Bumps the minimum Go module to 1.22.0 to allow for all patch versions in 1.22. Toolchain is using the latest 1.22.7
> all: Bump minimum Go module version to 1.22

- .changes/unreleased/NOTES-20241030-173604.yaml
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
Refs:
- https://github.com/hashicorp/terraform-plugin-go/pull/441
- https://developer.hashicorp.com/terraform/plugin/framework/migrating
- https://developer.hashicorp.com/terraform/plugin/mux
The upcoming versions of the plugin protocol (5.7/6.7) include support for ephemeral resource types. The `terraform-plugin-sdk` Go module will not be receiving this feature, however this Go module must be updated to handle the new RPCs with errors.
Provider developers can still implement ephemeral resource types in their `terraform-plugin-sdk` based providers by following the [framework migration documentation](https://developer.hashicorp.com/terraform/plugin/framework/migrating) to introduce `terraform-plugin-mux`, which then will enable `terraform-plugin-framework` based ephemeral resource …
> all: Initial ephemeral resource implementation

- .github/workflows/ci-go.yml
Previously, it was just using running a single test with the latest Terraform version that is installed on the machine.
We will have new functionality/new tests that need to run on newer Terraform versions after #1375
> chore: Update CI to run corner tests on all v5 protocol Terraform versions

- .golangci.yml
- helper/acctest/random_test.go
- helper/resource/plugin_test.go
- helper/resource/testcase_providers_test.go
- helper/resource/testcase_validate_test.go
- helper/resource/testing_test.go
- helper/resource/teststep_providers_test.go
- helper/resource/teststep_validate_test.go
- helper/schema/grpc_provider_test.go
- helper/schema/provider_test.go
- helper/structure/suppress_json_diff_test.go
- helper/validation/meta_test.go
- internal/configs/hcl2shim/flatmap_test.go
- internal/plugin/convert/diagnostics.go
Update golangci config and resolve `copyloopvar`
> chore: Update golangci-lint linters and apply fixes

- .changes/unreleased/BUG FIXES-20250218-172440.yaml
- .changes/unreleased/NOTES-20250218-172625.yaml
- helper/schema/schema.go
- helper/schema/schema_test.go
- website/docs/plugin/sdkv2/resources/write-only-arguments.mdx
- website/docs/plugin/sdkv2/schemas/schema-behaviors.mdx
Write-only attributes when used with ephemeral data cannot be used within any set and set-based data due to limitations in Terraform Core. This PR adds validation to block write-only attributes from being used within set nested blocks.
> helper/schema: Add validation to prevent write-only attributes in set nested blocks

- helper/validation/write_only.go
- website/docs/plugin/sdkv2/resources/write-only-arguments.mdx
Adds a callout for `PreferWriteOnlyAttribute()` validator usage about the persistent nature of the warnings for practitioners.
> Add callout for `PreferWriteOnlyAttribute` validator

- website/README.md
- website/docs/plugin/sdkv2/best-practices/deprecations.mdx
- website/docs/plugin/sdkv2/best-practices/detecting-drift.mdx
- website/docs/plugin/sdkv2/best-practices/index.mdx
- website/docs/plugin/sdkv2/debugging.mdx
- website/docs/plugin/sdkv2/guides/terraform-0.12-compatibility.mdx
- website/docs/plugin/sdkv2/guides/v1-upgrade-guide.mdx
- website/docs/plugin/sdkv2/guides/v2-upgrade-guide.mdx
- website/docs/plugin/sdkv2/index.mdx
- website/docs/plugin/sdkv2/logging/http-transport.mdx
- website/docs/plugin/sdkv2/logging/index.mdx
- website/docs/plugin/sdkv2/resources/customizing-differences.mdx
- website/docs/plugin/sdkv2/resources/data-consistency-errors.mdx
- website/docs/plugin/sdkv2/resources/import.mdx
- website/docs/plugin/sdkv2/resources/index.mdx
- website/docs/plugin/sdkv2/resources/retries-and-customizable-timeouts.mdx
- website/docs/plugin/sdkv2/resources/state-migration.mdx
- website/docs/plugin/sdkv2/resources/write-only-arguments.mdx
- website/docs/plugin/sdkv2/schemas/index.mdx
- website/docs/plugin/sdkv2/schemas/schema-behaviors.mdx
- website/docs/plugin/sdkv2/schemas/schema-methods.mdx
- website/docs/plugin/sdkv2/schemas/schema-types.mdx
- website/docs/plugin/sdkv2/testing/acceptance-tests/index.mdx
- website/docs/plugin/sdkv2/testing/acceptance-tests/sweepers.mdx
- website/docs/plugin/sdkv2/testing/acceptance-tests/testcase.mdx
- website/docs/plugin/sdkv2/testing/acceptance-tests/teststep.mdx
- website/docs/plugin/sdkv2/testing/index.mdx
- website/docs/plugin/sdkv2/testing/testing-api.mdx
- website/docs/plugin/sdkv2/testing/testing-patterns.mdx
- website/docs/plugin/sdkv2/testing/unit-testing.mdx
We are migrating the terraform-plugin-* documentation to a unified HashiCorp product documentation repository. As a result of this migration, the unified repo (web-unified-docs) will be the source of truth.
This PR adds a noticed to all existing MDX files in the original location so folks know where to contribute. We plan on deprecating and removing the files in /website.
This PR will be merged after docs have been migrated
> Add comments for UDR migration

- go.mod
- go.sum
Cross-reference:
https://github.com/hashicorp/go-cty/pull/6
https://github.com/hashicorp/go-cty/pull/7
https://github.com/hashicorp/go-cty/pull/8
https://github.com/hashicorp/go-cty/pull/9
https://github.com/hashicorp/go-cty/pull/10
> Update hashicorp/go-cty to v1.5.0

- .changes/unreleased/NOTES-20250319-150717.yaml
- go.mod
- go.sum
~depends on #1444~
* Updates `terraform-plugin-go` to the latest alpha release (instead of it pointing to a commit on main)
* Adds a changie entry for the changelog for the anticipated alpha release
> update terraform-plugin-go to v0.27.0-alpha.1 and add changie entry

- .github/CONTRIBUTING.md
- .github/workflows/release.yml
~Updated the file as per the `CONTRIBUTING.md` guide (at the very bottom)~
Adds support for pre-releases to Github Action
> Prepare 2.37.0-alpha.1 release

- helper/schema/core_schema.go
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
Return error diagnostics if there's no identity schema (or an empty one) defined when it should be.
Includes tests for this (`GetResourceIdentitySchemas`, `ReadResource`, `PlanResourceChange`, `ApplyResourceChange`)
Oh, and also adds an identity test for `ApplyResourceChange` that didn't exist yet.
> error if there's no identity schema (or an empty one) defined when it should be

- helper/schema/identity_data.go
- helper/schema/identity_data_test.go
- helper/schema/resource_data.go
This PR adds tests for `identity_data.go` inspired by existing tests for `resource_data.go`.
This uncovered a flaw in the current implementation, when it comes to non-string identity attributes which currently don't work.
To quote the relevant commit message on this:
>  Switch to using multiple field readers in IdentityData
>
> This resembles the behaviour in `ResourceData` more closely. Specifically,
this makes it possible to have number values in the source identity sent by
Terraform that are encoded as strings. Before this commit this failed as the
field writer does not allow to write strings for fields that are typed as
integers in the schema, which is what we did to initialize the result.
> TFECO-9157: Add tests for `identity_data.go` and switch to multiple field reader

- helper/schema/resource_data_test.go
> TFECO-9158: Add tests for ResourceData#Identity method

- helper/logging/logging_http_transport_test.go
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
- helper/schema/provider.go
- helper/schema/provider_test.go
- helper/schema/resource.go
- helper/schema/resource_importer.go
This PR adds a new `ImportStateWithIdentity` method to `Provider` which is used in the `ImportResourceState` RPC handler to optionally pass a resource identity instead of a string id. Both still exist side-by-side and will for backwards compatibility.
Resources can now retrieve and set values in an identity like this to support import by identity:
```golang
Importer: &schema.ResourceImporter{
StateContext: func(ctx context.Context, rd *schema.ResourceData, i interface{}) ([]*schema.ResourceData, error) {
if rd.Id() != "" {
return []*schema.ResourceData{rd}, nil // just return the resource data, since the string id is used
}
identity, err := rd.Identity()
if err != nil {
return nil, err
}
emailRaw, ok := identity.GetOk("email")
if !ok {
return nil, fmt.Errorf("error getting email from …
```
> support importing by resource identity

- helper/schema/provider.go
- helper/schema/resource_importer.go
- helper/schema/resource_importer_test.go
This PR adds support for `ImportStatePassthroughWithIdentity` which makes it easier to implement support for import by identity if the fallback `Id` attribute is part of the identity object (e.g. if it's a UUID or ARN that can just be copied as is from an attribute of the identity object into the Id string).
> TFECO-9286: add `ImportStatePassthroughWithIdentity`

- helper/schema/resource.go
This addresses the bug that I was running into when attempting to use write-only attributes on a no update function resource.
I get a passing `TestProvider` now after applying the changes and integrating the plugin-sdk that's set on my machine.
Fixes https://github.com/hashicorp/terraform-plugin-sdk/issues/1471
> add writeOnly in updateFuncSet check

- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
- helper/schema/resource.go
- terraform/state.go
_PR description shamelessly stolen from https://github.com/hashicorp/terraform-plugin-framework/pull/1137_
--- 
This PR re-introduces the validation that previously lived in Terraform core (removed in https://github.com/hashicorp/terraform/pull/36989), which ensures that resource identities do not change after Terraform core stores them in state.
The one tricky part of this PR is `ReadResource`, which the protocol currently does not have sufficient information for us to determine if the state we are refreshing has already been stored (typical use-case) or if we are importing the resource. Rather than loosening how strict the validation is, I added a temporary key to a framework reserved `private` field, which Terraform passes between `ImportResourceState -> ReadResource`. Once we've read …
> ResourceIdentity: Validate that identities do not change after Terraform stores it

- .changes/unreleased/ENHANCEMENTS-20250915-092938.yaml
- .changes/unreleased/ENHANCEMENTS-20250915-093208.yaml
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
No, this is a changelog PR
> changelog: add entries for #1508 and #1513

- .changes/unreleased/BUG FIXES-20250922-091942.yaml
- helper/schema/grpc_provider.go
- helper/schema/grpc_provider_test.go
Ref: https://github.com/hashicorp/terraform-provider-aws/issues/44182
There are some scenarios where an identity may be stored with all null values (a scenario that #1513 will prevent from occurring now), which should not be validated, since an identity with all null values is invalid.
No
> identity: Update change validation to ensure empty identities (all null attributes) are not validated
